/**
 * 테이블: `common_code`
 * DDL: 01-core-schema.sql
 * PK: INT (GENERATED BY DEFAULT AS IDENTITY)
 *
 * main_code + sub_code 조합으로 시스템 전역 코드값(상태, 단계, 권한 등)을 정의.
 */
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

/** 공통 코드 — main_code(5자) + sub_code 복합 식별 */
@Entity('common_code')
export class CommonCodeEntity {
  @PrimaryGeneratedColumn({ type: 'int' })
  id: number;

  /** 코드 그룹 (예: A0011, D0001) */
  @Column({ name: 'main_code', type: 'varchar', length: 5 })
  main_code: string;

  @Column({ name: 'sub_code', type: 'int' })
  sub_code: number;

  @Column({ name: 'code_name', type: 'varchar', length: 100 })
  code_name: string;

  /** 데이터 컬럼에 저장되는 영문 코드값 — ref_data1 컬럼 재사용 (예: open, assigned, planned) */
  @Column({ name: 'ref_data1', type: 'varchar', length: 100, default: '' })
  code_value: string;

  /** UI·드롭다운 정렬 순서 */
  @Column({ name: 'order_seq', type: 'int', default: 0 })
  order_seq: number;

  @Column({ name: 'is_use', type: 'boolean', default: true })
  is_use: boolean;
}
