/**
 * 테이블: `company`, `branch`, `site`
 * DDL: 01-core-schema.sql + 06-ui-portal-schema.sql (company/site 확장 컬럼)
 * PK: INT (각 테이블 GENERATED BY DEFAULT AS IDENTITY)
 *
 * 조직 계층: company → branch → site. site는 company_id 또는 branch 경유로 소속 결정.
 */
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

/** 고객사·계약사 등 법인/조직 단위 */
@Entity('company')
export class CompanyEntity {
  @PrimaryGeneratedColumn({ type: 'int' })
  id: number;

  @Column({ type: 'varchar', length: 64 })
  code: string;

  @Column({ name: 'company_name', type: 'varchar', length: 255 })
  company_name: string;

  /** 고객사 | 파트너 등 */
  @Column({ name: 'company_type', type: 'varchar', length: 24, nullable: true })
  company_type: string | null;

  /** SLA·서비스 등급 (Standard, Premium 등) */
  @Column({ name: 'contract_tier', type: 'varchar', length: 32, nullable: true })
  contract_tier: string | null;

  @Column({ name: 'region_label', type: 'varchar', length: 64, nullable: true })
  region_label: string | null;

  @Column({ name: 'is_use', type: 'boolean', default: true })
  is_use: boolean;

  @Column({ name: 'created_at', type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })
  created_at: Date;
}

/** 회사 산하 지점·영업소 */
@Entity('branch')
export class BranchEntity {
  @PrimaryGeneratedColumn({ type: 'int' })
  id: number;

  @Column({ type: 'varchar', length: 64 })
  code: string;

  @Column({ name: 'company_id', type: 'int' })
  company_id: number;

  @Column({ name: 'branch_name', type: 'varchar', length: 255 })
  branch_name: string;

  @Column({ name: 'is_use', type: 'boolean', default: true })
  is_use: boolean;
}

/** 단말이 배치되는 현장(병원·매장 등) */
@Entity('site')
export class SiteEntity {
  @PrimaryGeneratedColumn({ type: 'int' })
  id: number;

  @Column({ type: 'varchar', length: 64 })
  code: string;

  @Column({ name: 'site_name', type: 'varchar', length: 255 })
  site_name: string;

  /** 직접 소속 회사. branch 경유 시 NULL 가능 */
  @Column({ name: 'company_id', type: 'int', nullable: true })
  company_id: number | null;

  @Column({ name: 'branch_id', type: 'int', nullable: true })
  branch_id: number | null;

  @Column({ type: 'varchar', length: 512, nullable: true })
  address: string | null;

  @Column({ name: 'region_label', type: 'varchar', length: 64, nullable: true })
  region_label: string | null;

  /** 지리 구역 (기본 korea) */
  @Column({ name: 'geo_zone', type: 'varchar', length: 32, nullable: true })
  geo_zone: string | null;

  @Column({ name: 'is_use', type: 'boolean', default: true })
  is_use: boolean;

  @Column({ name: 'created_at', type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })
  created_at: Date;
}
