import type {
  Alarm,
  Customer,
  Equipment,
  Installation,
  ServiceTicket,
  Site,
} from "./types";

/** 멕시코 플릿·현장 샘플 */
export const mexicoEquipments: Equipment[] = [
  {
    id: "eq-mx-001",
    serialNo: "HK-2024-MX0158",
    model: "HAWKEYE 1625",
    customer: "Flex Guadalajara",
    site: "Guadalajara North Campus",
    region: "MX-JAL",
    geoZone: "mexico",
    status: "online",
    slaTier: "Critical",
    serviceability: "즉시 원격가능",
    lat: 20.66,
    lng: -103.35,
    tubeLifePct: 79,
    detectorLifePct: 84,
    lastTelemetryAt: "2026-06-05T22:25:00-06:00",
    firmwareVersion: "v3.2.1",
    installDate: "2024-04-12",
  },
  {
    id: "eq-mx-002",
    serialNo: "RP-2023-MX0892",
    model: "RAPIDER 225",
    customer: "Continental Automotive",
    site: "San Luis Potosí Plant",
    region: "MX-SLP",
    geoZone: "mexico",
    status: "alarm",
    slaTier: "High",
    serviceability: "당일 방문",
    lat: 22.16,
    lng: -100.99,
    tubeLifePct: 38,
    detectorLifePct: 55,
    lastTelemetryAt: "2026-06-05T22:24:00-06:00",
    firmwareVersion: "v2.8.4",
    installDate: "2023-10-08",
  },
  {
    id: "eq-mx-003",
    serialNo: "HK-2025-MX0201",
    model: "HAWKEYE 1300",
    customer: "Samsung SDI Mexico",
    site: "Tijuana Battery Park",
    region: "MX-BCN",
    geoZone: "mexico",
    status: "maintenance",
    slaTier: "Critical",
    serviceability: "부품 대기",
    lat: 32.51,
    lng: -117.04,
    tubeLifePct: 29,
    detectorLifePct: 88,
    lastTelemetryAt: "2026-06-05T21:50:00-06:00",
    firmwareVersion: "v3.1.0",
    installDate: "2025-01-22",
  },
  {
    id: "eq-mx-004",
    serialNo: "RP-2024-MX1103",
    model: "RAPIDER 160",
    customer: "Bosch México",
    site: "Querétaro Tech Center",
    region: "MX-QUE",
    geoZone: "mexico",
    status: "online",
    slaTier: "Standard",
    serviceability: "즉시 원격가능",
    lat: 20.59,
    lng: -100.39,
    tubeLifePct: 88,
    detectorLifePct: 76,
    lastTelemetryAt: "2026-06-05T22:26:00-06:00",
    firmwareVersion: "v3.0.2",
    installDate: "2024-08-05",
  },
  {
    id: "eq-mx-005",
    serialNo: "HK-2022-MX0045",
    model: "HAWKEYE 1625",
    customer: "APTIV Mexico",
    site: "Monterrey Operations",
    region: "MX-NLE",
    geoZone: "mexico",
    status: "safe_mode",
    slaTier: "High",
    serviceability: "익일 방문",
    lat: 25.69,
    lng: -100.32,
    tubeLifePct: 51,
    detectorLifePct: 44,
    lastTelemetryAt: "2026-06-05T22:20:00-06:00",
    firmwareVersion: "v2.9.1",
    installDate: "2022-07-14",
  },
  {
    id: "eq-mx-006",
    serialNo: "RP-2025-MX0312",
    model: "RAPIDER 225",
    customer: "Foxconn Mexico",
    site: "Chihuahua Campus",
    region: "MX-CHH",
    geoZone: "mexico",
    status: "offline",
    slaTier: "High",
    serviceability: "부품 대기",
    lat: 28.64,
    lng: -106.09,
    tubeLifePct: 67,
    detectorLifePct: 72,
    lastTelemetryAt: "2026-06-05T18:15:00-06:00",
    firmwareVersion: "v3.0.0",
    installDate: "2025-03-01",
  },
  {
    id: "eq-mx-007",
    serialNo: "HK-2024-MX0788",
    model: "HAWKEYE 1300",
    customer: "Visteon México",
    site: "Ciudad Juárez Plant",
    region: "MX-CHH",
    geoZone: "mexico",
    status: "online",
    slaTier: "Critical",
    serviceability: "즉시 원격가능",
    lat: 31.69,
    lng: -106.42,
    tubeLifePct: 74,
    detectorLifePct: 81,
    lastTelemetryAt: "2026-06-05T22:27:00-06:00",
    firmwareVersion: "v3.1.2",
    installDate: "2024-11-18",
  },
  {
    id: "eq-mx-008",
    serialNo: "RP-2024-MX0550",
    model: "RAPIDER 160",
    customer: "Denso Mexico",
    site: "Aguascalientes Plant",
    region: "MX-AGU",
    geoZone: "mexico",
    status: "online",
    slaTier: "Standard",
    serviceability: "즉시 원격가능",
    lat: 21.88,
    lng: -102.29,
    tubeLifePct: 91,
    detectorLifePct: 85,
    lastTelemetryAt: "2026-06-05T22:28:00-06:00",
    firmwareVersion: "v3.0.5",
    installDate: "2024-09-30",
  },
];

export const mexicoCustomers: Customer[] = [
  {
    id: "cust-mx-001",
    name: "Flex Guadalajara",
    type: "고객사",
    region: "MX-JAL",
    siteCount: 2,
    equipmentCount: 3,
    contractTier: "Critical",
    registeredAt: "2024-03-15",
  },
  {
    id: "cust-mx-002",
    name: "Continental Automotive",
    type: "고객사",
    region: "MX-SLP",
    siteCount: 1,
    equipmentCount: 2,
    contractTier: "High",
    registeredAt: "2023-08-20",
  },
  {
    id: "cust-mx-003",
    name: "Samsung SDI Mexico",
    type: "고객사",
    region: "MX-BCN",
    siteCount: 1,
    equipmentCount: 2,
    contractTier: "Critical",
    registeredAt: "2025-01-10",
  },
  {
    id: "cust-mx-004",
    name: "Bosch México",
    type: "고객사",
    region: "MX-QUE",
    siteCount: 2,
    equipmentCount: 4,
    contractTier: "Critical",
    registeredAt: "2024-05-01",
  },
  {
    id: "cust-mx-005",
    name: "TechValley Mexico S.A. de C.V.",
    type: "대리점",
    region: "MX",
    siteCount: 0,
    equipmentCount: 0,
    contractTier: "Standard",
    registeredAt: "2025-08-15",
  },
];

export const mexicoSites: Site[] = [
  {
    id: "site-mx-001",
    customerId: "cust-mx-001",
    customerName: "Flex Guadalajara",
    name: "Guadalajara North Campus",
    address: "Av. Mariano Otero 1249, Guadalajara, Jalisco",
    region: "MX-JAL",
    equipmentCount: 2,
    installedAt: "2024-05-01",
  },
  {
    id: "site-mx-002",
    customerId: "cust-mx-002",
    customerName: "Continental Automotive",
    name: "San Luis Potosí Plant",
    address: "Parque Industrial Logistik, San Luis Potosí",
    region: "MX-SLP",
    equipmentCount: 2,
    installedAt: "2023-11-12",
  },
  {
    id: "site-mx-003",
    customerId: "cust-mx-003",
    customerName: "Samsung SDI Mexico",
    name: "Tijuana Battery Park",
    address: "Blvd. Industrial 15001, Tijuana, Baja California",
    region: "MX-BCN",
    equipmentCount: 2,
    installedAt: "2025-02-01",
  },
  {
    id: "site-mx-004",
    customerId: "cust-mx-004",
    customerName: "Bosch México",
    name: "Querétaro Tech Center",
    address: "Av. Pie de la Cuesta 702, Querétaro",
    region: "MX-QUE",
    equipmentCount: 2,
    installedAt: "2024-09-10",
  },
  {
    id: "site-mx-005",
    customerId: "cust-mx-001",
    customerName: "Flex Guadalajara",
    name: "Monterrey Operations",
    address: "Parque Industrial FINSA, Monterrey, Nuevo León",
    region: "MX-NLE",
    equipmentCount: 1,
    installedAt: "2024-12-05",
  },
  {
    id: "site-mx-006",
    customerId: "cust-mx-004",
    customerName: "Foxconn Mexico",
    name: "Chihuahua Campus",
    address: "Complejo Industrial Chihuahua, Chihuahua",
    region: "MX-CHH",
    equipmentCount: 1,
    installedAt: "2025-03-15",
  },
];

export const mexicoAlarms: Alarm[] = [
  {
    id: "alm-mx-001",
    equipmentId: "eq-mx-002",
    equipmentSn: "RP-2023-MX0892",
    ruleName: "tube.kv.high",
    message: "Tube kV 182kV — threshold 180kV exceeded",
    severity: "critical",
    acknowledged: false,
    remoteAttempted: true,
    remoteResult: "pending",
    ticketId: "TKT-2026-MX4521",
    triggeredAt: "2026-06-05T21:48:00-06:00",
  },
  {
    id: "alm-mx-002",
    equipmentId: "eq-mx-006",
    equipmentSn: "RP-2025-MX0312",
    ruleName: "connectivity.offline",
    message: "Greengrass disconnected — edge gateway offline",
    severity: "warning",
    acknowledged: false,
    remoteAttempted: false,
    remoteResult: "pending",
    triggeredAt: "2026-06-05T18:10:00-06:00",
  },
];

export const mexicoServiceTickets: ServiceTicket[] = [
  {
    id: "TKT-2026-MX4521",
    alarmId: "alm-mx-001",
    equipmentSn: "RP-2023-MX0892",
    customer: "Continental Automotive",
    site: "San Luis Potosí Plant",
    symptom: "Tube kV over-threshold during production run",
    severity: "critical",
    slaTier: "High",
    serviceability: "당일 방문",
    stage: "출동",
    engineerName: "Carlos Mendoza",
    createdAt: "2026-06-05T21:50:00-06:00",
    slaDeadline: "2026-06-06T01:50:00-06:00",
    slaBreached: false,
  },
  {
    id: "TKT-2026-MX4480",
    equipmentSn: "HK-2025-MX0201",
    customer: "Samsung SDI Mexico",
    site: "Tijuana Battery Park",
    symptom: "Tube life below PM threshold — scheduled maintenance",
    severity: "warning",
    slaTier: "Critical",
    serviceability: "부품 대기",
    stage: "작업",
    engineerName: "Ana Rodríguez",
    createdAt: "2026-06-05T14:00:00-06:00",
    slaDeadline: "2026-06-07T14:00:00-06:00",
    slaBreached: false,
  },
];

export const mexicoInstallations: Installation[] = [
  {
    id: "inst-mx-001",
    orderRef: "SO-MX-2026-0092",
    equipmentSn: "HK-2026-MX0501",
    model: "HAWKEYE 1625",
    customer: "Denso Mexico",
    site: "Aguascalientes Plant",
    plannedInstallDate: "2026-06-11",
    status: "예정",
    iotRegistered: false,
  },
  {
    id: "inst-mx-002",
    orderRef: "SO-MX-2026-0081",
    equipmentSn: "RP-2026-MX0388",
    model: "RAPIDER 225",
    customer: "Visteon México",
    site: "Ciudad Juárez Plant",
    plannedInstallDate: "2026-06-10",
    actualInstallDate: "2026-06-10",
    status: "시운전",
    iotRegistered: false,
  },
];
