import type {
  Alarm,
  Customer,
  Equipment,
  Installation,
  ServiceTicket,
  Site,
} from "./types";

/** 동아시아(일본·중국) 플릿·현장 샘플 */
export const eastAsiaEquipments: Equipment[] = [
  {
    id: "eq-ea-001",
    serialNo: "HK-2024-JP0158",
    model: "HAWKEYE 1625",
    customer: "Sony Semiconductor",
    site: "Kumamoto Technology Center",
    region: "JP-43",
    geoZone: "east-asia",
    status: "online",
    slaTier: "Critical",
    serviceability: "즉시 원격가능",
    lat: 32.79,
    lng: 130.74,
    tubeLifePct: 83,
    detectorLifePct: 87,
    lastTelemetryAt: "2026-06-06T14:22:00+09:00",
    firmwareVersion: "v3.2.1",
    installDate: "2024-05-20",
  },
  {
    id: "eq-ea-002",
    serialNo: "RP-2023-JP0892",
    model: "RAPIDER 225",
    customer: "Renesas Electronics",
    site: "Naka Plant",
    region: "JP-08",
    geoZone: "east-asia",
    status: "alarm",
    slaTier: "High",
    serviceability: "당일 방문",
    lat: 36.05,
    lng: 140.5,
    tubeLifePct: 41,
    detectorLifePct: 59,
    lastTelemetryAt: "2026-06-06T14:20:00+09:00",
    firmwareVersion: "v2.8.4",
    installDate: "2023-09-15",
  },
  {
    id: "eq-ea-003",
    serialNo: "HK-2025-JP0201",
    model: "HAWKEYE 1300",
    customer: "Panasonic Industry",
    site: "Osaka Kadoma",
    region: "JP-27",
    geoZone: "east-asia",
    status: "maintenance",
    slaTier: "Critical",
    serviceability: "부품 대기",
    lat: 34.74,
    lng: 135.58,
    tubeLifePct: 33,
    detectorLifePct: 89,
    lastTelemetryAt: "2026-06-06T13:55:00+09:00",
    firmwareVersion: "v3.1.0",
    installDate: "2025-02-01",
  },
  {
    id: "eq-ea-004",
    serialNo: "RP-2024-JP1103",
    model: "RAPIDER 160",
    customer: "Tokyo Electron",
    site: "Yokohama HQ Campus",
    region: "JP-14",
    geoZone: "east-asia",
    status: "online",
    slaTier: "Standard",
    serviceability: "즉시 원격가능",
    lat: 35.44,
    lng: 139.64,
    tubeLifePct: 90,
    detectorLifePct: 78,
    lastTelemetryAt: "2026-06-06T14:25:00+09:00",
    firmwareVersion: "v3.0.2",
    installDate: "2024-07-10",
  },
  {
    id: "eq-ea-005",
    serialNo: "HK-2024-CN0158",
    model: "HAWKEYE 1625",
    customer: "SMIC Shanghai",
    site: "Shanghai Fab SN1",
    region: "CN-SH",
    geoZone: "east-asia",
    status: "online",
    slaTier: "Critical",
    serviceability: "즉시 원격가능",
    lat: 31.12,
    lng: 121.47,
    tubeLifePct: 76,
    detectorLifePct: 82,
    lastTelemetryAt: "2026-06-06T13:58:00+08:00",
    firmwareVersion: "v3.2.1",
    installDate: "2024-04-08",
  },
  {
    id: "eq-ea-006",
    serialNo: "RP-2023-CN0892",
    model: "RAPIDER 225",
    customer: "BOE Technology",
    site: "Beijing BDA Plant",
    region: "CN-BJ",
    geoZone: "east-asia",
    status: "alarm",
    slaTier: "High",
    serviceability: "당일 방문",
    lat: 39.79,
    lng: 116.51,
    tubeLifePct: 39,
    detectorLifePct: 54,
    lastTelemetryAt: "2026-06-06T13:56:00+08:00",
    firmwareVersion: "v2.8.4",
    installDate: "2023-10-22",
  },
  {
    id: "eq-ea-007",
    serialNo: "HK-2025-CN0201",
    model: "HAWKEYE 1300",
    customer: "BYD Semiconductor",
    site: "Shenzhen Pingshan",
    region: "CN-GD",
    geoZone: "east-asia",
    status: "safe_mode",
    slaTier: "High",
    serviceability: "익일 방문",
    lat: 22.69,
    lng: 114.35,
    tubeLifePct: 52,
    detectorLifePct: 47,
    lastTelemetryAt: "2026-06-06T13:50:00+08:00",
    firmwareVersion: "v3.1.0",
    installDate: "2025-01-18",
  },
  {
    id: "eq-ea-008",
    serialNo: "RP-2024-CN1103",
    model: "RAPIDER 160",
    customer: "TSMC Nanjing",
    site: "Nanjing Fab 16",
    region: "CN-JS",
    geoZone: "east-asia",
    status: "online",
    slaTier: "Critical",
    serviceability: "즉시 원격가능",
    lat: 32.06,
    lng: 118.78,
    tubeLifePct: 85,
    detectorLifePct: 80,
    lastTelemetryAt: "2026-06-06T13:59:00+08:00",
    firmwareVersion: "v3.0.5",
    installDate: "2024-09-25",
  },
];

export const eastAsiaCustomers: Customer[] = [
  {
    id: "cust-ea-001",
    name: "Sony Semiconductor",
    type: "고객사",
    region: "JP-43",
    siteCount: 1,
    equipmentCount: 2,
    contractTier: "Critical",
    registeredAt: "2024-03-01",
  },
  {
    id: "cust-ea-002",
    name: "Renesas Electronics",
    type: "고객사",
    region: "JP-08",
    siteCount: 2,
    equipmentCount: 3,
    contractTier: "High",
    registeredAt: "2023-07-15",
  },
  {
    id: "cust-ea-003",
    name: "SMIC Shanghai",
    type: "고객사",
    region: "CN-SH",
    siteCount: 2,
    equipmentCount: 4,
    contractTier: "Critical",
    registeredAt: "2024-02-20",
  },
  {
    id: "cust-ea-004",
    name: "BOE Technology",
    type: "고객사",
    region: "CN-BJ",
    siteCount: 1,
    equipmentCount: 2,
    contractTier: "High",
    registeredAt: "2023-11-05",
  },
  {
    id: "cust-ea-005",
    name: "TechValley East Asia Pte.",
    type: "대리점",
    region: "EA",
    siteCount: 0,
    equipmentCount: 0,
    contractTier: "Standard",
    registeredAt: "2025-06-01",
  },
];

export const eastAsiaSites: Site[] = [
  {
    id: "site-ea-001",
    customerId: "cust-ea-001",
    customerName: "Sony Semiconductor",
    name: "Kumamoto Technology Center",
    address: "4-14-1 Oaza Otsu, Kikuyo, Kumamoto, Japan",
    region: "JP-43",
    equipmentCount: 2,
    installedAt: "2024-06-01",
  },
  {
    id: "site-ea-002",
    customerId: "cust-ea-002",
    customerName: "Renesas Electronics",
    name: "Naka Plant",
    address: "2-16-1 Naka-shi, Ibaraki, Japan",
    region: "JP-08",
    equipmentCount: 2,
    installedAt: "2023-12-10",
  },
  {
    id: "site-ea-003",
    customerId: "cust-ea-002",
    customerName: "Tokyo Electron",
    name: "Yokohama HQ Campus",
    address: "2-12-1 Akasaka, Minato-ku, Tokyo, Japan",
    region: "JP-14",
    equipmentCount: 1,
    installedAt: "2024-08-15",
  },
  {
    id: "site-ea-004",
    customerId: "cust-ea-003",
    customerName: "SMIC Shanghai",
    name: "Shanghai Fab SN1",
    address: "No.18 Zhangjiang Road, Pudong, Shanghai, China",
    region: "CN-SH",
    equipmentCount: 2,
    installedAt: "2024-05-01",
  },
  {
    id: "site-ea-005",
    customerId: "cust-ea-004",
    customerName: "BOE Technology",
    name: "Beijing BDA Plant",
    address: "BDA, Daxing District, Beijing, China",
    region: "CN-BJ",
    equipmentCount: 2,
    installedAt: "2023-11-20",
  },
  {
    id: "site-ea-006",
    customerId: "cust-ea-003",
    customerName: "BYD Semiconductor",
    name: "Shenzhen Pingshan",
    address: "Pingshan District, Shenzhen, Guangdong, China",
    region: "CN-GD",
    equipmentCount: 1,
    installedAt: "2025-02-01",
  },
];

export const eastAsiaAlarms: Alarm[] = [
  {
    id: "alm-ea-001",
    equipmentId: "eq-ea-002",
    equipmentSn: "RP-2023-JP0892",
    ruleName: "tube.kv.high",
    message: "Tube kV threshold exceeded — remote calibration recommended",
    severity: "critical",
    acknowledged: false,
    remoteAttempted: true,
    remoteResult: "pending",
    ticketId: "TKT-2026-EA4521",
    triggeredAt: "2026-06-06T14:10:00+09:00",
  },
  {
    id: "alm-ea-002",
    equipmentId: "eq-ea-006",
    equipmentSn: "RP-2023-CN0892",
    ruleName: "detector.temp.high",
    message: "Detector temperature warning — 46.8°C",
    severity: "warning",
    acknowledged: false,
    remoteAttempted: false,
    triggeredAt: "2026-06-06T13:45:00+08:00",
  },
];

export const eastAsiaServiceTickets: ServiceTicket[] = [
  {
    id: "TKT-2026-EA4521",
    alarmId: "alm-ea-001",
    equipmentSn: "RP-2023-JP0892",
    customer: "Renesas Electronics",
    site: "Naka Plant",
    symptom: "Tube kV over-threshold during production",
    severity: "critical",
    slaTier: "High",
    serviceability: "당일 방문",
    stage: "출동",
    engineerName: "Ken Tanaka",
    createdAt: "2026-06-06T14:12:00+09:00",
    slaDeadline: "2026-06-06T18:12:00+09:00",
    slaBreached: false,
  },
  {
    id: "TKT-2026-EA4480",
    equipmentSn: "HK-2025-CN0201",
    customer: "BYD Semiconductor",
    site: "Shenzhen Pingshan",
    symptom: "Safe mode — motor coordinate drift detected",
    severity: "warning",
    slaTier: "Critical",
    serviceability: "부품 대기",
    stage: "작업",
    engineerName: "Li Wei",
    createdAt: "2026-06-06T11:00:00+08:00",
    slaDeadline: "2026-06-08T11:00:00+08:00",
    slaBreached: false,
  },
];

export const eastAsiaInstallations: Installation[] = [
  {
    id: "inst-ea-001",
    orderRef: "SO-EA-2026-0095",
    equipmentSn: "HK-2026-JP0501",
    model: "HAWKEYE 1625",
    customer: "Murata Manufacturing",
    site: "Fukui Plant",
    plannedInstallDate: "2026-06-13",
    status: "예정",
    iotRegistered: false,
  },
  {
    id: "inst-ea-002",
    orderRef: "SO-EA-2026-0082",
    equipmentSn: "RP-2026-CN0388",
    model: "RAPIDER 225",
    customer: "SMIC Shanghai",
    site: "Suzhou Fab",
    plannedInstallDate: "2026-06-11",
    actualInstallDate: "2026-06-11",
    status: "시운전",
    iotRegistered: false,
  },
];
