import type {
  Alarm,
  AlarmRule,
  AlgorithmConfig,
  AsRecord,
  CommonCode,
  Customer,
  Engineer,
  Equipment,
  FirmwareConfig,
  Installation,
  IotThingAuth,
  NotificationChannel,
  PartOrder,
  PartSchedule,
  PipelineStatus,
  ReportSummary,
  ServiceTicket,
  Site,
  TelemetrySnapshot,
  UserAccount,
  YieldRecord,
} from "./types";
import {
  eastAsiaAlarms,
  eastAsiaCustomers,
  eastAsiaEquipments,
  eastAsiaInstallations,
  eastAsiaServiceTickets,
  eastAsiaSites,
} from "./mock-data-east-asia";
import {
  europeAlarms,
  europeCustomers,
  europeEquipments,
  europeInstallations,
  europeServiceTickets,
  europeSites,
} from "./mock-data-europe";
import {
  mexicoAlarms,
  mexicoCustomers,
  mexicoEquipments,
  mexicoInstallations,
  mexicoServiceTickets,
  mexicoSites,
} from "./mock-data-mexico";

const baseEquipments: Equipment[] = [
  {
    id: "eq-001",
    serialNo: "HK-2024-00158",
    model: "HAWKEYE 1625",
    customer: "삼성전자 DS",
    site: "화성 Campus A",
    region: "경기",
    status: "online",
    slaTier: "Critical",
    serviceability: "즉시 원격가능",
    lat: 37.2,
    lng: 126.8,
    tubeLifePct: 72,
    detectorLifePct: 85,
    lastTelemetryAt: "2026-06-06T14:25:00+09:00",
    firmwareVersion: "v3.2.1",
    installDate: "2024-03-15",
  },
  {
    id: "eq-002",
    serialNo: "RP-2023-00892",
    model: "RAPIDER 225",
    customer: "LG이노텍",
    site: "구미 2공장",
    region: "경북",
    status: "alarm",
    slaTier: "High",
    serviceability: "당일 방문",
    lat: 36.1,
    lng: 128.4,
    tubeLifePct: 45,
    detectorLifePct: 62,
    lastTelemetryAt: "2026-06-06T14:24:30+09:00",
    firmwareVersion: "v2.8.4",
    installDate: "2023-11-20",
  },
  {
    id: "eq-003",
    serialNo: "HK-2025-00201",
    model: "HAWKEYE 1300",
    customer: "SK hynix",
    site: "이천 M15",
    region: "경기",
    status: "maintenance",
    slaTier: "Critical",
    serviceability: "부품 대기",
    lat: 37.3,
    lng: 127.4,
    tubeLifePct: 28,
    detectorLifePct: 91,
    lastTelemetryAt: "2026-06-06T13:50:00+09:00",
    firmwareVersion: "v3.1.0",
    installDate: "2025-01-10",
  },
  {
    id: "eq-004",
    serialNo: "RP-2024-01103",
    model: "RAPIDER 160",
    customer: "현대모비스",
    site: "울산 전장공장",
    region: "울산",
    status: "online",
    slaTier: "Standard",
    serviceability: "즉시 원격가능",
    lat: 35.5,
    lng: 129.3,
    tubeLifePct: 88,
    detectorLifePct: 79,
    lastTelemetryAt: "2026-06-06T14:26:00+09:00",
    firmwareVersion: "v3.0.2",
    installDate: "2024-08-05",
  },
  {
    id: "eq-005",
    serialNo: "HK-2022-00045",
    model: "HAWKEYE 1625",
    customer: "DB HiTek",
    site: "충북 음성",
    region: "충북",
    status: "safe_mode",
    slaTier: "High",
    serviceability: "익일 방문",
    lat: 36.9,
    lng: 127.7,
    tubeLifePct: 55,
    detectorLifePct: 48,
    lastTelemetryAt: "2026-06-06T14:20:00+09:00",
    firmwareVersion: "v2.9.1",
    installDate: "2022-06-18",
  },
  {
    id: "eq-006",
    serialNo: "RP-2025-00312",
    model: "RAPIDER 225",
    customer: "삼성SDI",
    site: "천안 Campus",
    region: "충남",
    status: "offline",
    slaTier: "High",
    serviceability: "부품 대기",
    lat: 36.8,
    lng: 127.1,
    tubeLifePct: 67,
    detectorLifePct: 73,
    lastTelemetryAt: "2026-06-06T11:30:00+09:00",
    firmwareVersion: "v3.2.0",
    installDate: "2025-04-22",
  },
];

const generatedEquipments: Equipment[] = Array.from({ length: 20 }, (_, i) => {
  const n = i + 7;
  const regions = ["경기", "경북", "충남", "울산", "전북", "강원", "전남", "충북"];
  const customers = ["삼성전자 DS", "LG이노텍", "SK hynix", "현대모비스", "DB HiTek"];
  const statuses: Equipment["status"][] = ["online", "online", "online", "maintenance", "alarm", "offline"];
  const region = regions[i % regions.length];
  const customer = customers[i % customers.length];
  const { lat, lng } = (() => {
    const bases: Record<string, { lat: number; lng: number }> = {
      경기: { lat: 37.28, lng: 127.02 },
      경북: { lat: 36.02, lng: 128.6 },
      충남: { lat: 36.45, lng: 127.12 },
      울산: { lat: 35.54, lng: 129.31 },
      전북: { lat: 35.82, lng: 127.11 },
      강원: { lat: 37.75, lng: 128.9 },
      전남: { lat: 34.82, lng: 126.89 },
      충북: { lat: 36.85, lng: 127.75 },
    };
    const base = bases[region];
    const angle = i * 2.399963;
    const r = 0.06 + (i % 3) * 0.04;
    return {
      lat: base.lat + Math.sin(angle) * r,
      lng: base.lng + Math.cos(angle) * r * 1.15,
    };
  })();
  return {
    id: `eq-${String(n).padStart(3, "0")}`,
    serialNo: `HK-2024-${String(200 + n).padStart(5, "0")}`,
    model: i % 2 === 0 ? "HAWKEYE 1625" : "RAPIDER 225",
    customer,
    site: `${region} Plant ${(i % 3) + 1}`,
    region,
    status: statuses[i % statuses.length],
    slaTier: i % 4 === 0 ? "Critical" : i % 3 === 0 ? "High" : "Standard",
    serviceability: i % 5 === 0 ? "부품 대기" : "즉시 원격가능",
    lat,
    lng,
    tubeLifePct: 25 + (i * 7) % 70,
    detectorLifePct: 30 + (i * 5) % 65,
    lastTelemetryAt: `2026-06-06T${String(10 + (i % 8)).padStart(2, "0")}:${String(i % 60).padStart(2, "0")}:00+09:00`,
    firmwareVersion: i % 2 === 0 ? "v3.2.1" : "v2.9.1",
    installDate: `2024-${String((i % 12) + 1).padStart(2, "0")}-15`,
  };
});

export const equipments: Equipment[] = [
  ...baseEquipments,
  ...generatedEquipments,
  ...eastAsiaEquipments,
  ...europeEquipments,
  ...mexicoEquipments,
];

export const telemetrySnapshots: TelemetrySnapshot[] = equipments.map((eq) => ({
  equipmentId: eq.id,
  tubeKv: eq.status === "alarm" ? 185 : 160,
  tubeMa: eq.status === "alarm" ? 4.2 : 3.5,
  tubeSec: 0.8,
  detectorTemp: eq.status === "alarm" ? 48.5 : 38.2,
  bodyTemp: 42.1,
  uptimeHours: 12450,
  yieldPct: eq.status === "alarm" ? 87.2 : 96.5,
  receivedAt: eq.lastTelemetryAt,
}));

export const alarms: Alarm[] = [
  {
    id: "alm-001",
    equipmentId: "eq-002",
    equipmentSn: "RP-2023-00892",
    ruleName: "튜브 kV 임계 초과",
    severity: "critical",
    message: "튜브 kV 185kV — 임계값 180kV 초과",
    triggeredAt: "2026-06-06T14:18:00+09:00",
    acknowledged: true,
    remoteAttempted: true,
    remoteResult: "unresolved",
    ticketId: "TKT-2026-004521",
  },
  {
    id: "alm-002",
    equipmentId: "eq-005",
    equipmentSn: "HK-2022-00045",
    ruleName: "디텍터 온도 경고",
    severity: "warning",
    message: "디텍터 온도 46°C — 경고 임계 45°C",
    triggeredAt: "2026-06-06T13:55:00+09:00",
    acknowledged: false,
    remoteAttempted: false,
  },
  {
    id: "alm-003",
    equipmentId: "eq-003",
    equipmentSn: "HK-2025-00201",
    ruleName: "튜브 수명 임박",
    severity: "warning",
    message: "튜브 잔여 수명 28% — 교체 권고",
    triggeredAt: "2026-06-06T09:00:00+09:00",
    acknowledged: true,
    remoteAttempted: false,
    ticketId: "TKT-2026-004518",
  },
  {
    id: "alm-004",
    equipmentId: "eq-006",
    equipmentSn: "RP-2025-00312",
    ruleName: "네트워크 단절",
    severity: "critical",
    message: "Greengrass 연결 끊김 — 스풀 버퍼 2.4MB",
    triggeredAt: "2026-06-06T11:30:00+09:00",
    acknowledged: true,
    remoteAttempted: false,
    ticketId: "TKT-2026-004515",
  },
  ...eastAsiaAlarms,
  ...europeAlarms,
  ...mexicoAlarms,
];

export const alarmRules: AlarmRule[] = [
  {
    id: "rule-001",
    name: "튜브 kV 임계 초과",
    target: "tube",
    condition: "tube.kv > 180",
    severity: "critical",
    enabled: true,
    notifyChannels: ["SNS", "SES", "Dashboard"],
    triggerRemote: true,
    triggerTicket: true,
  },
  {
    id: "rule-002",
    name: "디텍터 온도 경고",
    target: "detector",
    condition: "detector.temp > 45",
    severity: "warning",
    enabled: true,
    notifyChannels: ["Dashboard", "SES"],
    triggerRemote: true,
    triggerTicket: false,
  },
  {
    id: "rule-003",
    name: "튜브 수명 임박",
    target: "tube",
    condition: "tube.life_pct < 30",
    severity: "warning",
    enabled: true,
    notifyChannels: ["Dashboard"],
    triggerRemote: false,
    triggerTicket: true,
  },
  {
    id: "rule-004",
    name: "복합 — kV+온도 동시 이상",
    target: "composite",
    condition: "tube.kv > 170 AND detector.temp > 42",
    severity: "critical",
    enabled: true,
    notifyChannels: ["SNS", "SES", "Dashboard"],
    triggerRemote: true,
    triggerTicket: true,
  },
  {
    id: "rule-005",
    name: "네트워크 단절",
    target: "body",
    condition: "connectivity.status == offline AND duration > 300s",
    severity: "critical",
    enabled: true,
    notifyChannels: ["SNS", "Dashboard"],
    triggerRemote: false,
    triggerTicket: true,
  },
];

export const notificationChannels: NotificationChannel[] = [
  {
    id: "ch-001",
    name: "Critical SNS",
    type: "SNS",
    target: "arn:aws:sns:ap-northeast-2:123456789:tv-alarm-critical",
    severityFilter: ["critical"],
    recipients: "on-call 엔지니어 그룹",
    enabled: true,
    description: "Critical 알람 즉시 발송",
  },
  {
    id: "ch-002",
    name: "운영팀 이메일",
    type: "SES",
    target: "ops@techvalley.io",
    severityFilter: ["critical", "warning"],
    recipients: "운영팀 8명",
    enabled: true,
    description: "일일 알람 요약 포함",
  },
  {
    id: "ch-003",
    name: "관제 대시보드",
    type: "Dashboard",
    target: "in-app",
    severityFilter: ["critical", "warning"],
    recipients: "전체 로그인 사용자",
    enabled: true,
    description: "실시간 알람 패널·배지",
  },
  {
    id: "ch-004",
    name: "CS 티켓 Webhook",
    type: "Webhook",
    target: "https://api.techvalley.io/hooks/cs-alarm",
    severityFilter: ["critical"],
    recipients: "CS 자동 티켓 연계",
    enabled: true,
    description: "티켓 자동 발행 트리거",
  },
  {
    id: "ch-005",
    name: "Warning 전용 SES",
    type: "SES",
    target: "warning@techvalley.io",
    severityFilter: ["warning"],
    recipients: "엔지니어 팀",
    enabled: false,
    description: "Warning만 별도 수신 (비활성)",
  },
];

export const serviceTickets: ServiceTicket[] = [
  {
    id: "TKT-2026-004521",
    alarmId: "alm-001",
    equipmentSn: "RP-2023-00892",
    customer: "LG이노텍",
    site: "구미 2공장",
    symptom: "튜브 kV 임계 초과 — 원격 보정 실패",
    severity: "critical",
    slaTier: "High",
    serviceability: "당일 방문",
    createdAt: "2026-06-06T14:22:00+09:00",
    stage: "배정",
    engineerId: "eng-002",
    engineerName: "김민수",
    plannedDispatchAt: "2026-06-06T18:00:00+09:00",
    slaDeadline: "2026-06-07T06:22:00+09:00",
    slaBreached: false,
  },
  {
    id: "TKT-2026-004518",
    alarmId: "alm-003",
    equipmentSn: "HK-2025-00201",
    customer: "SK hynix",
    site: "이천 M15",
    symptom: "튜브 수명 28% — 교체 필요",
    severity: "warning",
    slaTier: "Critical",
    serviceability: "부품 대기",
    createdAt: "2026-06-06T09:15:00+09:00",
    stage: "작업",
    engineerId: "eng-001",
    engineerName: "박지훈",
    plannedDispatchAt: "2026-06-07T09:00:00+09:00",
    actualDispatchAt: "2026-06-07T09:30:00+09:00",
    plannedCompleteAt: "2026-06-07T17:00:00+09:00",
    slaDeadline: "2026-06-07T09:15:00+09:00",
    slaBreached: false,
  },
  {
    id: "TKT-2026-004515",
    alarmId: "alm-004",
    equipmentSn: "RP-2025-00312",
    customer: "삼성SDI",
    site: "천안 Campus",
    symptom: "네트워크 단절 — Greengrass 재동기화 필요",
    severity: "critical",
    slaTier: "High",
    serviceability: "부품 대기",
    createdAt: "2026-06-06T11:35:00+09:00",
    stage: "접수",
    slaDeadline: "2026-06-07T03:35:00+09:00",
    slaBreached: false,
  },
  {
    id: "TKT-2026-004510",
    equipmentSn: "HK-2024-00158",
    customer: "삼성전자 DS",
    site: "화성 Campus A",
    symptom: "정기 PM — 튜브 보정",
    severity: "warning",
    slaTier: "Critical",
    serviceability: "즉시 원격가능",
    createdAt: "2026-06-05T10:00:00+09:00",
    stage: "완료",
    engineerId: "eng-003",
    engineerName: "이서연",
    plannedDispatchAt: "2026-06-05T14:00:00+09:00",
    actualDispatchAt: "2026-06-05T14:00:00+09:00",
    plannedCompleteAt: "2026-06-05T16:00:00+09:00",
    slaDeadline: "2026-06-05T10:15:00+09:00",
    slaBreached: false,
  },
  ...eastAsiaServiceTickets,
  ...europeServiceTickets,
  ...mexicoServiceTickets,
];

export const engineers: Engineer[] = [
  {
    id: "eng-001",
    name: "박지훈",
    region: "경기",
    specialty: ["튜브 교체", "HAWKEYE"],
    status: "작업중",
    assignedTickets: 2,
  },
  {
    id: "eng-002",
    name: "김민수",
    region: "경북",
    specialty: ["RAPIDER", "원격진단"],
    status: "출동가능",
    assignedTickets: 1,
  },
  {
    id: "eng-003",
    name: "이서연",
    region: "경기",
    specialty: ["PM", "펌웨어"],
    status: "출동가능",
    assignedTickets: 0,
  },
  {
    id: "eng-004",
    name: "최현우",
    region: "충남",
    specialty: ["네트워크", "Greengrass"],
    status: "출동가능",
    assignedTickets: 0,
  },
];

export const partOrders: PartOrder[] = [
  {
    id: "PR-2026-00892",
    ticketId: "TKT-2026-004518",
    equipmentSn: "HK-2025-00201",
    partNo: "TUBE-HK-225",
    partName: "X-ray Tube 225kV",
    qty: 1,
    status: "운송중",
    requestedAt: "2026-06-06T10:00:00+09:00",
    plannedShipDate: "2026-06-06",
    actualShipDate: "2026-06-06",
    plannedDeliveryDate: "2026-06-07",
    carrier: "CJ대한통운",
    trackingNo: "123456789012",
  },
  {
    id: "PR-2026-00885",
    ticketId: "TKT-2026-004515",
    equipmentSn: "RP-2025-00312",
    partNo: "PCB-GG-CORE",
    partName: "Greengrass Core Module",
    qty: 1,
    status: "확정",
    requestedAt: "2026-06-06T12:00:00+09:00",
    plannedShipDate: "2026-06-07",
    plannedDeliveryDate: "2026-06-08",
  },
];

export const partSchedules: PartSchedule[] = [
  {
    id: "sch-001",
    orderId: "PR-2026-00892",
    ticketId: "TKT-2026-004518",
    equipmentSn: "HK-2025-00201",
    customer: "SK hynix",
    site: "이천 M15",
    partName: "X-ray Tube 225kV",
    eta: "2026-06-07",
    visitPlannedAt: "2026-06-07",
    engineerName: "박지훈",
    delayDays: 0,
    podStatus: "운송중",
    carrier: "CJ대한통운",
    trackingNo: "123456789012",
  },
  {
    id: "sch-002",
    orderId: "PR-2026-00885",
    ticketId: "TKT-2026-004515",
    equipmentSn: "RP-2025-00312",
    customer: "삼성SDI",
    site: "천안 Campus",
    partName: "Greengrass Core Module",
    eta: "2026-06-08",
    visitPlannedAt: "2026-06-09",
    engineerName: "최현우",
    delayDays: 1,
    podStatus: "확정",
  },
  {
    id: "sch-003",
    orderId: "PR-2026-00880",
    ticketId: "TKT-2026-004521",
    equipmentSn: "RP-2023-00892",
    customer: "LG이노텍",
    site: "구미 2공장",
    partName: "Detector Panel RP-160",
    eta: "2026-06-06",
    visitPlannedAt: "2026-06-06",
    visitActualAt: "2026-06-06",
    engineerName: "김민수",
    delayDays: 0,
    podStatus: "교체완료",
    carrier: "한진택배",
    trackingNo: "987654321098",
  },
];

export const installations: Installation[] = [
  {
    id: "inst-001",
    orderRef: "SO-2026-0158",
    equipmentSn: "HK-2026-00501",
    model: "HAWKEYE 1625",
    customer: "삼성전자 DS",
    site: "평택 P4",
    plannedInstallDate: "2026-06-10",
    status: "예정",
    iotRegistered: false,
  },
  {
    id: "inst-002",
    orderRef: "SO-2026-0142",
    equipmentSn: "RP-2026-00388",
    model: "RAPIDER 225",
    customer: "LG이노텍",
    site: "파주 Campus",
    plannedInstallDate: "2026-06-08",
    actualInstallDate: "2026-06-08",
    status: "시운전",
    iotRegistered: false,
  },
  {
    id: "inst-003",
    orderRef: "SO-2026-0120",
    equipmentSn: "HK-2026-00455",
    model: "HAWKEYE 1300",
    customer: "SK hynix",
    site: "청주 M12X",
    plannedInstallDate: "2026-06-03",
    actualInstallDate: "2026-06-03",
    status: "완료",
    iotRegistered: true,
  },
  ...eastAsiaInstallations,
  ...europeInstallations,
  ...mexicoInstallations,
];

export const asRecords: AsRecord[] = [
  {
    id: "as-001",
    ticketId: "TKT-2026-004510",
    equipmentSn: "HK-2024-00158",
    customer: "삼성전자 DS",
    completedAt: "2026-06-05T16:30:00+09:00",
    workSummary: "튜브 kV/mA 보정 및 PM 완료",
    replacedParts: [],
    satisfaction: 5,
    recurrence: false,
    normalRestored: true,
  },
  {
    id: "as-002",
    ticketId: "TKT-2026-004480",
    equipmentSn: "RP-2023-00892",
    customer: "LG이노텍",
    completedAt: "2026-05-28T15:00:00+09:00",
    workSummary: "디텍터 교체 및 캘리브레이션",
    replacedParts: ["DET-RP-160"],
    satisfaction: 4,
    recurrence: false,
    normalRestored: true,
  },
];

export const customers: Customer[] = [
  {
    id: "cust-001",
    name: "삼성전자 DS",
    type: "고객사",
    region: "경기",
    siteCount: 4,
    equipmentCount: 12,
    contractTier: "Critical",
    registeredAt: "2024-03-15",
  },
  {
    id: "cust-002",
    name: "LG이노텍",
    type: "고객사",
    region: "경북",
    siteCount: 3,
    equipmentCount: 8,
    contractTier: "High",
    registeredAt: "2025-01-20",
  },
  {
    id: "cust-003",
    name: "SK hynix",
    type: "고객사",
    region: "경기",
    siteCount: 5,
    equipmentCount: 15,
    contractTier: "Critical",
    registeredAt: "2026-04-10",
  },
  {
    id: "cust-004",
    name: "테크밸리코리아",
    type: "대리점",
    region: "전국",
    siteCount: 0,
    equipmentCount: 0,
    contractTier: "Standard",
    registeredAt: "2026-05-28",
  },
  ...eastAsiaCustomers,
  ...europeCustomers,
  ...mexicoCustomers,
];

export const sites: Site[] = [
  {
    id: "site-001",
    customerId: "cust-001",
    customerName: "삼성전자 DS",
    name: "화성 Campus A",
    address: "경기 화성시",
    region: "경기",
    equipmentCount: 3,
    installedAt: "2024-06-01",
  },
  {
    id: "site-002",
    customerId: "cust-002",
    customerName: "LG이노텍",
    name: "구미 2공장",
    address: "경북 구미시",
    region: "경북",
    equipmentCount: 2,
    installedAt: "2025-02-14",
  },
  {
    id: "site-003",
    customerId: "cust-003",
    customerName: "SK hynix",
    name: "이천 M15",
    address: "경기 이천시",
    region: "경기",
    equipmentCount: 4,
    installedAt: "2026-05-02",
  },
  {
    id: "site-004",
    customerId: "cust-001",
    customerName: "삼성전자 DS",
    name: "평택 P3",
    address: "경기 평택시",
    region: "경기",
    equipmentCount: 5,
    installedAt: "2026-06-01",
  },
  ...eastAsiaSites,
  ...europeSites,
  ...mexicoSites,
];

export const pipelineStatuses: PipelineStatus[] = [
  {
    tier: "Hot",
    store: "DocumentDB",
    retention: "7일",
    recordCount: 2840000,
    lagMs: 120,
    status: "healthy",
  },
  {
    tier: "Warm",
    store: "Aurora PostgreSQL",
    retention: "7~90일",
    recordCount: 12500000,
    lagMs: 450,
    status: "healthy",
  },
  {
    tier: "Cold",
    store: "Iceberg / S3",
    retention: "90일+",
    recordCount: 89000000,
    lagMs: 0,
    status: "healthy",
  },
];

export const yieldRecords: YieldRecord[] = [
  {
    id: "yld-001",
    equipmentSn: "HK-2024-00158",
    lotNo: "LOT-20260606-A",
    serialNo: "SN-882910",
    yieldPct: 96.5,
    inspectedAt: "2026-06-06T14:00:00+09:00",
    algorithmVersion: "v2.1.0",
  },
  {
    id: "yld-002",
    equipmentSn: "RP-2023-00892",
    lotNo: "LOT-20260606-B",
    serialNo: "SN-882911",
    yieldPct: 87.2,
    inspectedAt: "2026-06-06T13:45:00+09:00",
    algorithmVersion: "v2.1.0",
  },
];

export const reports: ReportSummary[] = [
  { id: "rpt-001", name: "튜브 로그", category: "장비", lastGenerated: "2026-06-06", recordCount: 15420 },
  { id: "rpt-002", name: "디텍터 로그", category: "장비", lastGenerated: "2026-06-06", recordCount: 12380 },
  { id: "rpt-003", name: "권역별 사용내역", category: "운영", lastGenerated: "2026-06-05", recordCount: 890 },
  { id: "rpt-004", name: "장비별 이상집계", category: "알람", lastGenerated: "2026-06-06", recordCount: 245 },
  { id: "rpt-005", name: "권역별 A/S 교체집계", category: "AS", lastGenerated: "2026-06-05", recordCount: 67 },
  { id: "rpt-006", name: "수율(Yield) 집계", category: "검사", lastGenerated: "2026-06-06", recordCount: 3420 },
];

export const users: UserAccount[] = [
  {
    id: "usr-001",
    name: "관리자",
    email: "admin@techvalley.io",
    role: "시스템 관리자",
    region: "전체",
    active: true,
    mfaEnabled: true,
  },
  {
    id: "usr-002",
    name: "박지훈",
    email: "park@techvalley.io",
    role: "서비스 엔지니어",
    region: "경기",
    active: true,
    mfaEnabled: true,
  },
  {
    id: "usr-003",
    name: "김상담",
    email: "cs@techvalley.io",
    role: "상담·CS",
    region: "전체",
    active: true,
    mfaEnabled: false,
  },
];

export const commonCodes: CommonCode[] = [
  { id: "SLA_TIER-Critical", group: "SLA_TIER", code: "Critical", name: "Critical", sort: 1, active: true },
  { id: "SLA_TIER-High", group: "SLA_TIER", code: "High", name: "High", sort: 2, active: true },
  { id: "SLA_TIER-Standard", group: "SLA_TIER", code: "Standard", name: "Standard", sort: 3, active: true },
  { id: "REGION-KR-GG", group: "REGION", code: "KR-GG", name: "경기", sort: 1, active: true },
  { id: "REGION-KR-GB", group: "REGION", code: "KR-GB", name: "경북", sort: 2, active: true },
  { id: "PART_TYPE-TUBE", group: "PART_TYPE", code: "TUBE", name: "튜브", sort: 1, active: true },
  { id: "PART_TYPE-DET", group: "PART_TYPE", code: "DET", name: "디텍터", sort: 2, active: true },
  { id: "ALARM_SEV-CRIT", group: "ALARM_SEV", code: "critical", name: "Critical", sort: 1, active: true },
  { id: "ALARM_SEV-WARN", group: "ALARM_SEV", code: "warning", name: "Warning", sort: 2, active: true },
];

export const algorithmConfigs: AlgorithmConfig[] = [
  { id: "alg-001", name: "Yield Standard", version: "v2.1.0", threshold: 92, status: "active", appliedEquipmentCount: 128 },
  { id: "alg-002", name: "Yield Strict", version: "v2.2.0-beta", threshold: 95, status: "staging", appliedEquipmentCount: 12 },
  { id: "alg-003", name: "Defect Edge Detect", version: "v1.4.2", threshold: 88, status: "active", appliedEquipmentCount: 86 },
  { id: "alg-004", name: "Legacy Yield", version: "v1.9.0", threshold: 90, status: "disabled", appliedEquipmentCount: 0 },
];

export const firmwareConfigs: FirmwareConfig[] = equipments.slice(0, 12).map((eq, i) => ({
  id: `fw-${eq.id}`,
  serialNo: eq.serialNo,
  model: eq.model,
  customer: eq.customer,
  current: eq.firmwareVersion,
  target: i % 3 === 0 ? "v3.2.2" : eq.firmwareVersion,
  auto: i % 4 === 0 ? "ON" : "OFF",
  lastCheckAt: eq.lastTelemetryAt,
}));

export const iotThings: IotThingAuth[] = equipments.slice(0, 10).map((eq) => ({
  id: `thing-${eq.id}`,
  sn: eq.serialNo,
  thing: `tv-${eq.serialNo.toLowerCase().replace(/-/g, "")}`,
  cert: `cert-${eq.id.slice(-6)}…`,
  policy: eq.slaTier === "Critical" ? "tv-critical-policy" : "tv-standard-policy",
  status: eq.status === "offline" ? "disconnected" : eq.status === "maintenance" ? "pending" : "connected",
  lastSeenAt: eq.lastTelemetryAt,
}));

export const slaDefinitions = [
  {
    tier: "Critical" as const,
    target: "안전·생산 직결 장비",
    firstResponse: "≤ 15분",
    dispatch: "≤ 4시간",
    recovery: "≤ 24시간",
    uptime: "99.5%+",
  },
  {
    tier: "High" as const,
    target: "주력 검사 장비",
    firstResponse: "≤ 30분",
    dispatch: "≤ 8시간(익일)",
    recovery: "≤ 48시간",
    uptime: "99.0%+",
  },
  {
    tier: "Standard" as const,
    target: "일반 장비",
    firstResponse: "≤ 2시간",
    dispatch: "≤ 2영업일",
    recovery: "≤ 5영업일",
    uptime: "97.0%+",
  },
];

