import type {
  Alarm,
  Customer,
  Equipment,
  Installation,
  ServiceTicket,
  Site,
} from "./types";

/** 유럽 플릿·현장 샘플 */
export const europeEquipments: Equipment[] = [
  {
    id: "eq-eu-001",
    serialNo: "HK-2024-EU0158",
    model: "HAWKEYE 1625",
    customer: "Infineon Technologies",
    site: "Dresden Fab 28",
    region: "DE-SN",
    geoZone: "europe",
    status: "online",
    slaTier: "Critical",
    serviceability: "즉시 원격가능",
    lat: 51.05,
    lng: 13.74,
    tubeLifePct: 81,
    detectorLifePct: 88,
    lastTelemetryAt: "2026-06-06T07:25:00+02:00",
    firmwareVersion: "v3.2.1",
    installDate: "2024-05-10",
  },
  {
    id: "eq-eu-002",
    serialNo: "RP-2023-EU0892",
    model: "RAPIDER 225",
    customer: "Bosch Mobility",
    site: "Stuttgart Plant 5",
    region: "DE-BW",
    geoZone: "europe",
    status: "alarm",
    slaTier: "High",
    serviceability: "당일 방문",
    lat: 48.78,
    lng: 9.18,
    tubeLifePct: 42,
    detectorLifePct: 58,
    lastTelemetryAt: "2026-06-06T07:24:30+02:00",
    firmwareVersion: "v2.8.4",
    installDate: "2023-09-12",
  },
  {
    id: "eq-eu-003",
    serialNo: "HK-2025-EU0201",
    model: "HAWKEYE 1300",
    customer: "STMicroelectronics",
    site: "Crolles Crolles2",
    region: "FR-ARA",
    geoZone: "europe",
    status: "maintenance",
    slaTier: "Critical",
    serviceability: "부품 대기",
    lat: 45.48,
    lng: 5.85,
    tubeLifePct: 31,
    detectorLifePct: 90,
    lastTelemetryAt: "2026-06-06T06:50:00+02:00",
    firmwareVersion: "v3.1.0",
    installDate: "2025-02-18",
  },
  {
    id: "eq-eu-004",
    serialNo: "RP-2024-EU1103",
    model: "RAPIDER 160",
    customer: "ASML Veldhoven",
    site: "Veldhoven HQ Campus",
    region: "NL-NB",
    geoZone: "europe",
    status: "online",
    slaTier: "Standard",
    serviceability: "즉시 원격가능",
    lat: 51.41,
    lng: 5.39,
    tubeLifePct: 86,
    detectorLifePct: 77,
    lastTelemetryAt: "2026-06-06T07:26:00+02:00",
    firmwareVersion: "v3.0.2",
    installDate: "2024-07-22",
  },
  {
    id: "eq-eu-005",
    serialNo: "HK-2022-EU0045",
    model: "HAWKEYE 1625",
    customer: "Siemens Digital Industries",
    site: "Erlangen Campus",
    region: "DE-BY",
    geoZone: "europe",
    status: "safe_mode",
    slaTier: "High",
    serviceability: "익일 방문",
    lat: 49.59,
    lng: 11.01,
    tubeLifePct: 53,
    detectorLifePct: 46,
    lastTelemetryAt: "2026-06-06T07:20:00+02:00",
    firmwareVersion: "v2.9.1",
    installDate: "2022-08-30",
  },
  {
    id: "eq-eu-006",
    serialNo: "RP-2025-EU0312",
    model: "RAPIDER 225",
    customer: "NXP Semiconductors",
    site: "Eindhoven HT",
    region: "NL-NB",
    geoZone: "europe",
    status: "offline",
    slaTier: "High",
    serviceability: "부품 대기",
    lat: 51.44,
    lng: 5.48,
    tubeLifePct: 64,
    detectorLifePct: 71,
    lastTelemetryAt: "2026-06-06T04:30:00+02:00",
    firmwareVersion: "v3.2.0",
    installDate: "2025-03-14",
  },
  {
    id: "eq-eu-007",
    serialNo: "HK-2024-EU0288",
    model: "HAWKEYE 1625",
    customer: "Continental AG",
    site: "Regensburg Plant",
    region: "DE-BY",
    geoZone: "europe",
    status: "online",
    slaTier: "Standard",
    serviceability: "즉시 원격가능",
    lat: 49.02,
    lng: 12.10,
    tubeLifePct: 74,
    detectorLifePct: 82,
    lastTelemetryAt: "2026-06-06T07:22:00+02:00",
    firmwareVersion: "v3.2.1",
    installDate: "2024-11-05",
  },
  {
    id: "eq-eu-008",
    serialNo: "RP-2024-EU0455",
    model: "RAPIDER 225",
    customer: "Schaeffler Group",
    site: "Herzogenaurach",
    region: "DE-BY",
    geoZone: "europe",
    status: "online",
    slaTier: "High",
    serviceability: "즉시 원격가능",
    lat: 49.57,
    lng: 10.88,
    tubeLifePct: 69,
    detectorLifePct: 75,
    lastTelemetryAt: "2026-06-06T07:23:00+02:00",
    firmwareVersion: "v3.1.2",
    installDate: "2024-04-18",
  },
];

export const europeCustomers: Customer[] = [
  {
    id: "cust-eu-001",
    name: "Infineon Technologies",
    type: "고객사",
    region: "DE-SN",
    siteCount: 2,
    equipmentCount: 4,
    contractTier: "Critical",
    registeredAt: "2024-04-01",
  },
  {
    id: "cust-eu-002",
    name: "Bosch Mobility",
    type: "고객사",
    region: "DE-BW",
    siteCount: 3,
    equipmentCount: 6,
    contractTier: "High",
    registeredAt: "2023-11-15",
  },
  {
    id: "cust-eu-003",
    name: "STMicroelectronics",
    type: "고객사",
    region: "FR-ARA",
    siteCount: 2,
    equipmentCount: 5,
    contractTier: "Critical",
    registeredAt: "2025-01-08",
  },
  {
    id: "cust-eu-004",
    name: "ASML Veldhoven",
    type: "고객사",
    region: "NL-NB",
    siteCount: 1,
    equipmentCount: 3,
    contractTier: "Critical",
    registeredAt: "2024-06-20",
  },
  {
    id: "cust-eu-005",
    name: "TechValley Europe GmbH",
    type: "대리점",
    region: "EU",
    siteCount: 0,
    equipmentCount: 0,
    contractTier: "Standard",
    registeredAt: "2025-09-01",
  },
];

export const europeSites: Site[] = [
  {
    id: "site-eu-001",
    customerId: "cust-eu-001",
    customerName: "Infineon Technologies",
    name: "Dresden Fab 28",
    address: "Königsbrücker Str. 180, Dresden, Germany",
    region: "DE-SN",
    equipmentCount: 2,
    installedAt: "2024-06-01",
  },
  {
    id: "site-eu-002",
    customerId: "cust-eu-002",
    customerName: "Bosch Mobility",
    name: "Stuttgart Plant 5",
    address: "Robert-Bosch-Platz 1, Stuttgart, Germany",
    region: "DE-BW",
    equipmentCount: 2,
    installedAt: "2023-12-10",
  },
  {
    id: "site-eu-003",
    customerId: "cust-eu-003",
    customerName: "STMicroelectronics",
    name: "Crolles Crolles2",
    address: "12 Chemin des Femmes, Crolles, France",
    region: "FR-ARA",
    equipmentCount: 2,
    installedAt: "2025-03-01",
  },
  {
    id: "site-eu-004",
    customerId: "cust-eu-004",
    customerName: "ASML Veldhoven",
    name: "Veldhoven HQ Campus",
    address: "De Run 6501, Veldhoven, Netherlands",
    region: "NL-NB",
    equipmentCount: 2,
    installedAt: "2024-08-15",
  },
  {
    id: "site-eu-005",
    customerId: "cust-eu-001",
    customerName: "Infineon Technologies",
    name: "Regensburg Plant",
    address: "Daimlerstr. 2, Regensburg, Germany",
    region: "DE-BY",
    equipmentCount: 2,
    installedAt: "2024-11-20",
  },
  {
    id: "site-eu-006",
    customerId: "cust-eu-002",
    customerName: "Siemens Digital Industries",
    name: "Erlangen Campus",
    address: "Werner-von-Siemens-Str. 1, Erlangen, Germany",
    region: "DE-BY",
    equipmentCount: 1,
    installedAt: "2022-09-05",
  },
];

export const europeAlarms: Alarm[] = [
  {
    id: "alm-eu-001",
    equipmentId: "eq-eu-002",
    equipmentSn: "RP-2023-EU0892",
    ruleName: "detector.temp.high",
    message: "Detector temperature threshold exceeded (48.2°C)",
    severity: "critical",
    acknowledged: false,
    remoteAttempted: true,
    remoteResult: "pending",
    ticketId: "TKT-2026-EU4521",
    triggeredAt: "2026-06-06T06:48:00+02:00",
  },
  {
    id: "alm-eu-002",
    equipmentId: "eq-eu-006",
    equipmentSn: "RP-2025-EU0312",
    ruleName: "connectivity.offline",
    message: "Connectivity lost — edge gateway offline",
    severity: "warning",
    acknowledged: false,
    remoteAttempted: false,
    remoteResult: "pending",
    triggeredAt: "2026-06-06T03:15:00+02:00",
  },
];

export const europeServiceTickets: ServiceTicket[] = [
  {
    id: "TKT-2026-EU4521",
    alarmId: "alm-eu-001",
    equipmentSn: "RP-2023-EU0892",
    customer: "Bosch Mobility",
    site: "Stuttgart Plant 5",
    symptom: "Detector over-temperature during high-load inspection",
    severity: "critical",
    slaTier: "High",
    serviceability: "당일 방문",
    stage: "출동",
    engineerName: "Thomas Weber",
    createdAt: "2026-06-06T06:50:00+02:00",
    slaDeadline: "2026-06-06T10:50:00+02:00",
    slaBreached: false,
  },
  {
    id: "TKT-2026-EU4480",
    equipmentSn: "HK-2025-EU0201",
    customer: "STMicroelectronics",
    site: "Crolles Crolles2",
    symptom: "Tube life below PM threshold — scheduled maintenance",
    severity: "warning",
    slaTier: "Critical",
    serviceability: "부품 대기",
    stage: "작업",
    engineerName: "Marie Dupont",
    createdAt: "2026-06-05T14:00:00+02:00",
    slaDeadline: "2026-06-07T14:00:00+02:00",
    slaBreached: false,
  },
];

export const europeInstallations: Installation[] = [
  {
    id: "inst-eu-001",
    orderRef: "SO-EU-2026-0088",
    equipmentSn: "HK-2026-EU0501",
    model: "HAWKEYE 1625",
    customer: "NXP Semiconductors",
    site: "Eindhoven HT",
    plannedInstallDate: "2026-06-12",
    status: "예정",
    iotRegistered: false,
  },
  {
    id: "inst-eu-002",
    orderRef: "SO-EU-2026-0075",
    equipmentSn: "RP-2026-EU0388",
    model: "RAPIDER 225",
    customer: "Continental AG",
    site: "Regensburg Plant",
    plannedInstallDate: "2026-06-09",
    actualInstallDate: "2026-06-09",
    status: "시운전",
    iotRegistered: false,
  },
];
