/**
 * 테이블: `device`
 * DDL: 01-core-schema.sql + 06-ui-portal-schema.sql (`portal_meta` 컬럼)
 * PK: INT (GENERATED BY DEFAULT AS IDENTITY)
 */
import { Column, Entity, JoinColumn, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import { SiteEntity } from '../../organization/entities/organization.entities';
import { ProductEntity } from '../../catalog/entities/catalog.entities';

/** 단말 마스터 — device_code가 MQTT·DocumentDB SSOT */
@Entity('device')
export class DeviceEntity {
  @PrimaryGeneratedColumn({ type: 'int' })
  id: number;

  /** 단말 문자열 고유값 (UK). DocumentDB·MQTT 토픽 SSOT */
  @Column({ name: 'device_code', type: 'varchar', length: 64 })
  device_code: string;

  /** 배치 현장 FK → site.id. 출고 전 NULL 가능 */
  @Column({ name: 'site_id', type: 'int', nullable: true })
  site_id: number | null;

  @Column({ name: 'product_id', type: 'int' })
  product_id: number;

  @Column({ type: 'varchar', length: 128 })
  serial: string;

  /** A0011 sub_code. 1=operational, 2=non_operational */
  @Column({ name: 'operational_status_type', type: 'int', default: 1 })
  operational_status_type: number;

  @Column({ name: 'firmware_version', type: 'varchar', length: 64, nullable: true })
  firmware_version: string | null;

  /** 최근 통신 시각. 통신 품질·온라인 판단 */
  @Column({ name: 'last_seen_at', type: 'timestamp', nullable: true })
  last_seen_at: Date | null;

  /** false 이면 포털·API·배치 대상에서 제외 */
  @Column({ name: 'is_use', type: 'boolean', default: true })
  is_use: boolean;

  /** UI Equipment: lat/lng, tubeLifePct, status, slaTier 등 */
  @Column({ name: 'portal_meta', type: 'jsonb', default: {} })
  portal_meta: Record<string, unknown>;

  @ManyToOne(() => SiteEntity, { nullable: true })
  @JoinColumn({ name: 'site_id' })
  site?: SiteEntity;

  @ManyToOne(() => ProductEntity)
  @JoinColumn({ name: 'product_id' })
  product?: ProductEntity;
}
