# shellcheck shell=bash
# Techvalley 로컬 인프라 포트 SSOT — 다른 프로젝트와 충돌 방지
# (mobi 25432, fota 5433/27018/9090, cesco 3306/27017 등 회피)
TV_PUBLISH_HOST="${TV_PUBLISH_HOST:-127.0.0.1}"
TV_POSTGRES_PORT="${TV_POSTGRES_PORT:-35432}"
TV_MONGO_PORT="${TV_MONGO_PORT:-37017}"
TV_MINIO_API_PORT="${TV_MINIO_API_PORT:-39100}"
TV_MINIO_CONSOLE_PORT="${TV_MINIO_CONSOLE_PORT:-39101}"

export TV_PUBLISH_HOST TV_POSTGRES_PORT TV_MONGO_PORT TV_MINIO_API_PORT TV_MINIO_CONSOLE_PORT

TV_POSTGRES_URI="${TV_POSTGRES_URI:-postgresql://tv:tv_local_dev@${TV_PUBLISH_HOST}:${TV_POSTGRES_PORT}/iot_analytics}"
TV_MONGO_URI="${TV_MONGO_URI:-mongodb://tv:tv_local_dev@${TV_PUBLISH_HOST}:${TV_MONGO_PORT}/iot_service?authSource=admin&directConnection=true}"
MINIO_ENDPOINT="${MINIO_ENDPOINT:-http://${TV_PUBLISH_HOST}:${TV_MINIO_API_PORT}}"
MINIO_CONSOLE="${MINIO_CONSOLE:-http://${TV_PUBLISH_HOST}:${TV_MINIO_CONSOLE_PORT}}"

export TV_POSTGRES_URI TV_MONGO_URI MINIO_ENDPOINT MINIO_CONSOLE

# bootstrap-postgres.sh 호환
PGHOST="${PGHOST:-$TV_PUBLISH_HOST}"
PGPORT="${PGPORT:-$TV_POSTGRES_PORT}"
PGUSER="${PGUSER:-tv}"
PGPASSWORD="${PGPASSWORD:-tv_local_dev}"
PGDATABASE="${PGDATABASE:-iot_analytics}"
MONGO_URI="${MONGO_URI:-$TV_MONGO_URI}"

export PGHOST PGPORT PGUSER PGPASSWORD PGDATABASE MONGO_URI
