/**
 * 테이블: `user`
 * DDL: 01-core-schema.sql
 * PK: INT (GENERATED BY DEFAULT AS IDENTITY)
 */
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

/** 포털·백오피스 사용자 계정 */
@Entity('user')
export class UserEntity {
  @PrimaryGeneratedColumn({ type: 'int' })
  id: number;

  @Column({ type: 'varchar', length: 64 })
  code: string;

  @Column({ type: 'varchar', length: 255, nullable: true })
  email: string | null;

  @Column({ name: 'user_name', type: 'varchar', length: 255, nullable: true })
  user_name: string | null;

  /** 인증 방식 타입 (내부 common_code) */
  @Column({ name: 'auth_type', type: 'int', default: 1 })
  auth_type: number;

  @Column({ name: 'is_use', type: 'boolean', default: true })
  is_use: boolean;

  @Column({ name: 'account_status', type: 'varchar', length: 32, default: 'active' })
  account_status: string;

  /** bcrypt 해시 — NULL 이면 Cognito/데모 로그인 전용 */
  @Column({ name: 'password_hash', type: 'varchar', length: 255, nullable: true })
  password_hash: string | null;

  /** Cognito sub — SSO 계정 UK */
  @Column({ name: 'sso_id', type: 'varchar', length: 128, nullable: true })
  sso_id: string | null;

  /** JWT claim siteId 캐시 (RBAC SSOT는 member) */
  @Column({ name: 'scope_site_id', type: 'int', nullable: true })
  scope_site_id: number | null;
}
