-- =============================================================================
-- 테크밸리(Techvalley) IoT·운영 포털 Aurora 코어 스키마 (PostgreSQL)
-- 적용: 01 → 02 → 04 → (선택) 05-seed-dev.sql
-- SSOT: 02.arch/config/schema/postgres/
-- UI 매핑: company→branch→site→device (customers/installation/equipment), device_code = MQTT S/N
-- 파이프라인 DLQ: DocumentDB pipeline_dlq_events (RDS 아님)
-- =============================================================================

-- public."user" (PostgreSQL reserved — 따옴표 필수)
CREATE TABLE public."user" (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code varchar(64) NOT NULL,
	email varchar(255) NULL,
	user_name varchar(255) NULL,
	sso_id varchar(255) NULL,
	password_hash varchar(255) NULL,
	auth_type int4 DEFAULT 1 NOT NULL,
	is_use bool DEFAULT true NOT NULL,
	account_status varchar(32) DEFAULT 'active'::character varying NOT NULL,
	email_verified_at timestamp(3) NULL,
	email_verify_token_hash varchar(64) NULL,
	email_verify_expires_at timestamp(3) NULL,
	approved_at timestamp(3) NULL,
	approved_by_user_id int4 NULL,
	rejected_at timestamp(3) NULL,
	rejected_by_user_id int4 NULL,
	remark varchar(256) NULL,
	scope_site_id int4 NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT uk_users_code UNIQUE (code),
	CONSTRAINT uk_users_sso_id UNIQUE (sso_id),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT fk_users_approved_by FOREIGN KEY (approved_by_user_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_users_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_users_rejected_by FOREIGN KEY (rejected_by_user_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_users_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT chk_users_auth_type CHECK (auth_type IN (1, 9, 10))
);
COMMENT ON COLUMN public."user".id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY). 로그인 계정 SSOT';
COMMENT ON COLUMN public."user".code IS '사용자 코드 (업무용, 예: USR-00001)';
COMMENT ON COLUMN public."user".email IS '이메일';
COMMENT ON COLUMN public."user".user_name IS '이름';
COMMENT ON COLUMN public."user".sso_id IS 'SSO 식별자 (Cognito sub 등). UK — 동일 IdP 계정 1 user 행. NULL 은 비-SSO 계정(여러 행 허용)';
COMMENT ON COLUMN public."user".password_hash IS 'bcrypt 해시 (NULL=SSO/Cognito 전용)';
COMMENT ON COLUMN public."user".auth_type IS 'A0001 sub_code(사용자 권한 유형). 1=user, 9=admin, 10=system_admin(가입 승인·플랫폼). member.auth_type 과 동일 코드표. 조직 역할 SSOT는 member.member_role_type(A0006)';
COMMENT ON COLUMN public."user".is_use IS '사용여부';
COMMENT ON COLUMN public."user".account_status IS 'active|pending_verify_email|pending_approval|rejected';
COMMENT ON COLUMN public."user".email_verified_at IS '이메일 인증 완료 시각';
COMMENT ON COLUMN public."user".email_verify_token_hash IS '이메일 인증 토큰 SHA-256(hex)';
COMMENT ON COLUMN public."user".email_verify_expires_at IS '이메일 인증 토큰 만료 시각';
COMMENT ON COLUMN public."user".approved_at IS 'system_admin 가입 승인 시각';
COMMENT ON COLUMN public."user".approved_by_user_id IS 'FK → "user".id (승인자)';
COMMENT ON COLUMN public."user".rejected_at IS '가입 거절 시각';
COMMENT ON COLUMN public."user".rejected_by_user_id IS 'FK → "user".id (거절 처리자)';
COMMENT ON COLUMN public."user".remark IS '내부 관리용';
COMMENT ON COLUMN public."user".scope_site_id IS '레거시 현장 스코프 캐시(선택). 회사·지점은 site·branch FK 로 유도. RBAC SSOT 는 member';
COMMENT ON COLUMN public."user".created_id IS '등록자("user".id)';
COMMENT ON COLUMN public."user".updated_id IS '수정자("user".id)';
COMMENT ON COLUMN public."user".created_at IS '생성 시각';
COMMENT ON COLUMN public."user".updated_at IS '수정 시각';

CREATE INDEX idx_users_auth_type ON public."user" USING btree (auth_type);
CREATE INDEX idx_users_account_status ON public."user" USING btree (account_status);
CREATE INDEX idx_users_created_at ON public."user" USING btree (created_at);
CREATE INDEX idx_users_created_id ON public."user" USING btree (created_id);
CREATE INDEX idx_users_is_use ON public."user" USING btree (is_use);
CREATE INDEX idx_users_scope_site ON public."user" USING btree (scope_site_id);
CREATE INDEX idx_users_updated_id ON public."user" USING btree (updated_id);
COMMENT ON TABLE public."user" IS '로그인·계정(인증·승인). 조직 멤버십·권한은 member·member_permission(A0005~A0007). 공통코드: 미사용';

-- public.common_code
CREATE TABLE public.common_code (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	main_code varchar(5) NOT NULL,
	sub_code int4 NOT NULL,
	code_name varchar(100) DEFAULT ''::character varying NOT NULL,
	code_name_en varchar(100) DEFAULT ''::character varying NOT NULL,
	languages_code jsonb NULL,
	order_seq int4 DEFAULT 0 NOT NULL,
	ref_data1 varchar(100) DEFAULT ''::character varying NOT NULL,
	ref_data2 varchar(50) DEFAULT ''::character varying NOT NULL,
	ref_data3 varchar(50) DEFAULT ''::character varying NOT NULL,
	is_use bool DEFAULT true NOT NULL,
	remark varchar(256) NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT common_code_pkey PRIMARY KEY (id),
	CONSTRAINT uk_common_code UNIQUE (main_code, sub_code),
	CONSTRAINT fk_common_code_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_common_code_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.common_code.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.common_code.main_code IS '그룹 코드(5자). UK (main_code, sub_code)의 그룹 축';
COMMENT ON COLUMN public.common_code.sub_code IS '그룹 내 숫자형 안정 코드. -1=그룹 헤더, 1 이상=실제 코드(A0005 sub_code 등)';
COMMENT ON COLUMN public.common_code.code_name IS '한글 표시명 (UI·리포트)';
COMMENT ON COLUMN public.common_code.code_name_en IS '영문 표시명';
COMMENT ON COLUMN public.common_code.languages_code IS '추가 locale 별칭 JSON (선택)';
COMMENT ON COLUMN public.common_code.order_seq IS '그룹 내 정렬. 헤더 로우는 -1, 사용 코드는 1 이상 권장';
COMMENT ON COLUMN public.common_code.ref_data1 IS '앱 매핑 값 1 (예: alarm.read_site, factory)';
COMMENT ON COLUMN public.common_code.ref_data2 IS '앱 매핑 값 2 (보조)';
COMMENT ON COLUMN public.common_code.ref_data3 IS '앱 매핑 값 3 (보조)';
COMMENT ON COLUMN public.common_code.is_use IS '사용 여부. false 이면 포털·API·배치 대상에서 제외';
COMMENT ON COLUMN public.common_code.remark IS '내부 운영·관리 메모';
COMMENT ON COLUMN public.common_code.created_id IS '등록자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.common_code.updated_id IS '수정자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.common_code.created_at IS '생성 시각 (timestamp(3), 앱에서 명시 설정)';
COMMENT ON COLUMN public.common_code.updated_at IS '최종 수정 시각 (timestamp(3), 앱에서 명시 설정)';

CREATE INDEX idx_common_code_main ON public.common_code USING btree (main_code);
COMMENT ON TABLE public.common_code IS '공통코드(메인/서브). 업무 불변 식별: (main_code, sub_code). 그룹 헤더 sub_code=-1. 예: S0001 사이트유형, A0005 권한, D0001 단말단계';

-- public.company
CREATE TABLE public.company (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code varchar(64) NOT NULL,
	company_name varchar(255) NOT NULL,
	description varchar(512) NULL,
	is_use bool DEFAULT true NOT NULL,
	remark varchar(256) NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT companies_pkey PRIMARY KEY (id),
	CONSTRAINT uk_companies_code UNIQUE (code),
	CONSTRAINT fk_companies_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_companies_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.company.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.company.code IS '회사 업무 코드 (UK). 외부 연동·포털 표시 키';
COMMENT ON COLUMN public.company.company_name IS '회사 표시 명칭';
COMMENT ON COLUMN public.company.description IS '회사 설명 (선택)';
COMMENT ON COLUMN public.company.is_use IS '사용 여부. false 이면 포털·API·배치 대상에서 제외';
COMMENT ON COLUMN public.company.remark IS '내부 운영·관리 메모';
COMMENT ON COLUMN public.company.created_id IS '등록자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.company.updated_id IS '수정자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.company.created_at IS '생성 시각 (timestamp(3), 앱에서 명시 설정)';
COMMENT ON COLUMN public.company.updated_at IS '최종 수정 시각 (timestamp(3), 앱에서 명시 설정)';

CREATE INDEX idx_companies_created_id ON public.company USING btree (created_id);
CREATE INDEX idx_companies_is_use ON public.company USING btree (is_use);
CREATE INDEX idx_companies_updated_id ON public.company USING btree (updated_id);
COMMENT ON TABLE public.company IS '회사(테넌트 조직 최상위). member·notification.company_id 스냅샷 기준';

-- public.language (알람 메시지·page_language FK 기준)
CREATE TABLE public.language (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code varchar(16) NOT NULL,
	language_name varchar(64) NOT NULL,
	locale varchar(16) NULL,
	is_default bool DEFAULT false NOT NULL,
	sort_order int4 DEFAULT 0 NOT NULL,
	is_use bool DEFAULT true NOT NULL,
	remark varchar(256) NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT languages_pkey PRIMARY KEY (id),
	CONSTRAINT uk_languages_code UNIQUE (code),
	CONSTRAINT fk_languages_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_languages_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.language.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.language.code IS '언어 코드 (UK, 예: ko, en)';
COMMENT ON COLUMN public.language.language_name IS '언어 표시명';
COMMENT ON COLUMN public.language.locale IS 'BCP47 locale (선택, 예: ko-KR)';
COMMENT ON COLUMN public.language.is_default IS '기본 언어 여부 (포털·알림 fallback)';
COMMENT ON COLUMN public.language.sort_order IS '언어 선택 UI 정렬';
COMMENT ON COLUMN public.language.is_use IS '사용 여부. false 이면 포털·API·배치 대상에서 제외';
COMMENT ON COLUMN public.language.remark IS '내부 운영·관리 메모';
COMMENT ON COLUMN public.language.created_id IS '등록자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.language.updated_id IS '수정자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.language.created_at IS '생성 시각 (timestamp(3), 앱에서 명시 설정)';
COMMENT ON COLUMN public.language.updated_at IS '최종 수정 시각 (timestamp(3), 앱에서 명시 설정)';

COMMENT ON TABLE public.language IS '지원 언어 마스터. alert·page_language FK 기준';

-- public.page_language (언어 참조는 language.id 만 — code FK 제거)
CREATE TABLE public.page_language (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	page_namespace varchar(32) NOT NULL,
	message_key varchar(128) NOT NULL,
	language_id int4 NOT NULL,
	message text NOT NULL,
	is_use bool DEFAULT true NOT NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT pages_languages_pkey PRIMARY KEY (id),
	CONSTRAINT uk_pages_languages UNIQUE (page_namespace, message_key, language_id),
	CONSTRAINT fk_pages_languages_language FOREIGN KEY (language_id) REFERENCES public.language(id) ON DELETE RESTRICT
);
COMMENT ON COLUMN public.page_language.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.page_language.page_namespace IS 'UI 페이지 네임스페이스 (UK 복합)';
COMMENT ON COLUMN public.page_language.message_key IS '메시지 키 (UK 복합)';
COMMENT ON COLUMN public.page_language.language_id IS '언어 FK → language.id (RESTRICT)';
COMMENT ON COLUMN public.page_language.message IS '번역 문구 본문';
COMMENT ON COLUMN public.page_language.is_use IS '사용 여부. false 이면 포털·API·배치 대상에서 제외';
COMMENT ON COLUMN public.page_language.created_at IS '생성 시각 (timestamp(3), 앱에서 명시 설정)';
COMMENT ON COLUMN public.page_language.updated_at IS '최종 수정 시각 (timestamp(3), 앱에서 명시 설정)';

COMMENT ON TABLE public.page_language IS '페이지 UI 문구 다국어. UK (page_namespace, message_key, language_id)';

-- public.website_menu (레거시 cescoservice.site_menu → tenant_id 축)
CREATE TABLE public.website_menu (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	tenant_id int8 NOT NULL,
	menu_code varchar(20) NOT NULL,
	menu_name varchar(30) NOT NULL,
	menu_name_en varchar(100) NULL,
	site_url varchar(50) NULL,
	menu_level int4 NULL,
	icon varchar(20) NULL,
	image_url varchar(50) NULL,
	parent_menu_code varchar(20) NULL,
	remark varchar(200) NULL,
	is_use bool DEFAULT true NOT NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT website_menu_pkey PRIMARY KEY (id),
	CONSTRAINT uk_website_menu_tenant_code UNIQUE (tenant_id, menu_code),
	CONSTRAINT fk_website_menu_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_website_menu_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.website_menu.id IS 'Surrogate PK';
COMMENT ON COLUMN public.website_menu.tenant_id IS '테넌트·프로젝트 축 (레거시 project_code). member.tenant_id 와 동일';
COMMENT ON COLUMN public.website_menu.menu_code IS '메뉴 업무 코드 (UK 복합). 트리: 상위보다 자릿수 긴 코드(레거시 level≈자릿수/2)';
COMMENT ON COLUMN public.website_menu.menu_name IS '메뉴명 (한글)';
COMMENT ON COLUMN public.website_menu.menu_name_en IS '메뉴 영문명';
COMMENT ON COLUMN public.website_menu.site_url IS '포털 라우트·사이트 URL 경로';
COMMENT ON COLUMN public.website_menu.menu_level IS '메뉴 트리 depth (표시·정렬 보조)';
COMMENT ON COLUMN public.website_menu.icon IS '아이콘 클래스·코드';
COMMENT ON COLUMN public.website_menu.image_url IS '아이콘 이미지 경로';
COMMENT ON COLUMN public.website_menu.parent_menu_code IS '상위 메뉴 menu_code (동일 tenant)';
COMMENT ON COLUMN public.website_menu.remark IS '비고';
COMMENT ON COLUMN public.website_menu.is_use IS '사용 여부';
COMMENT ON COLUMN public.website_menu.created_id IS '등록자 FK → user.id';
COMMENT ON COLUMN public.website_menu.updated_id IS '수정자 FK → user.id';
COMMENT ON COLUMN public.website_menu.created_at IS '등록 시각';
COMMENT ON COLUMN public.website_menu.updated_at IS '수정 시각';
CREATE INDEX idx_website_menu_tenant ON public.website_menu USING btree (tenant_id);
CREATE INDEX idx_website_menu_parent ON public.website_menu USING btree (tenant_id, parent_menu_code);
COMMENT ON TABLE public.website_menu IS '포털 웹 메뉴 트리 (레거시 MySQL site_menu). tenant별 UK menu_code';

-- public.website_group (레거시 MySQL site_group — member.website_group_id FK 대상)
CREATE TABLE public.website_group (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	tenant_id int8 NOT NULL,
	group_code varchar(20) NOT NULL,
	group_name varchar(40) NOT NULL,
	group_seq int4 NOT NULL,
	auth_type int4 DEFAULT 1 NOT NULL,
	remark varchar(200) DEFAULT ''::character varying NOT NULL,
	is_use bool DEFAULT true NOT NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT website_group_pkey PRIMARY KEY (id),
	CONSTRAINT uk_website_group_tenant_code UNIQUE (tenant_id, group_code),
	CONSTRAINT chk_website_group_auth_type CHECK (auth_type IN (1, 9)),
	CONSTRAINT fk_website_group_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_website_group_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.website_group.id IS 'Surrogate PK. member.website_group_id 가 참조';
COMMENT ON COLUMN public.website_group.tenant_id IS '테넌트·프로젝트 축 (레거시 project_code)';
COMMENT ON COLUMN public.website_group.group_code IS '그룹 업무 코드 (UK 복합)';
COMMENT ON COLUMN public.website_group.group_name IS '그룹 표시명 (역할·메뉴 묶음 라벨)';
COMMENT ON COLUMN public.website_group.group_seq IS '그룹 정렬 순번';
COMMENT ON COLUMN public.website_group.auth_type IS 'common_code main_code=A0001(사용자 권한 유형) sub_code. 본 그룹에 매핑 가능한 member.auth_type 과 동일해야 함. 코드표: 1=일반사용자(user) 9=관리자(admin). 레거시 A001';
COMMENT ON COLUMN public.website_group.remark IS '비고';
COMMENT ON COLUMN public.website_group.is_use IS '사용 여부';
COMMENT ON COLUMN public.website_group.created_id IS '등록자 FK → user.id';
COMMENT ON COLUMN public.website_group.updated_id IS '수정자 FK → user.id';
COMMENT ON COLUMN public.website_group.created_at IS '등록 시각';
COMMENT ON COLUMN public.website_group.updated_at IS '수정 시각';
CREATE INDEX idx_website_group_tenant ON public.website_group USING btree (tenant_id);
CREATE INDEX idx_website_group_auth_type ON public.website_group USING btree (tenant_id, auth_type);
COMMENT ON TABLE public.website_group IS '포털 메뉴 권한 그룹. auth_type(A0001)별 메뉴 CRUD 묶음. member.website_group_id 로 멤버에 배정';

-- public.website_group_menu (레거시 MySQL site_group_menu)
CREATE TABLE public.website_group_menu (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	tenant_id int8 NOT NULL,
	group_id int4 NOT NULL,
	menu_id int4 NOT NULL,
	is_insert bool DEFAULT true NOT NULL,
	is_modify bool DEFAULT true NOT NULL,
	is_delete bool DEFAULT true NOT NULL,
	is_excel bool DEFAULT true NOT NULL,
	is_print bool DEFAULT true NOT NULL,
	is_comment bool DEFAULT true NOT NULL,
	is_download bool DEFAULT true NOT NULL,
	is_special bool DEFAULT true NOT NULL,
	is_use bool DEFAULT true NOT NULL,
	created_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT website_group_menu_pkey PRIMARY KEY (id),
	CONSTRAINT uk_website_group_menu UNIQUE (tenant_id, group_id, menu_id),
	CONSTRAINT fk_website_group_menu_group FOREIGN KEY (group_id) REFERENCES public.website_group(id) ON DELETE CASCADE,
	CONSTRAINT fk_website_group_menu_menu FOREIGN KEY (menu_id) REFERENCES public.website_menu(id) ON DELETE CASCADE,
	CONSTRAINT fk_website_group_menu_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.website_group_menu.id IS 'Surrogate PK';
COMMENT ON COLUMN public.website_group_menu.tenant_id IS '테넌트 축 (group·menu tenant 와 일치 필수 — 앱 검증)';
COMMENT ON COLUMN public.website_group_menu.group_id IS 'FK → website_group.id';
COMMENT ON COLUMN public.website_group_menu.menu_id IS 'FK → website_menu.id';
COMMENT ON COLUMN public.website_group_menu.is_insert IS '추가(등록) 권한';
COMMENT ON COLUMN public.website_group_menu.is_modify IS '수정 권한';
COMMENT ON COLUMN public.website_group_menu.is_delete IS '삭제 권한';
COMMENT ON COLUMN public.website_group_menu.is_excel IS '엑셀 다운로드 권한';
COMMENT ON COLUMN public.website_group_menu.is_print IS '출력 권한';
COMMENT ON COLUMN public.website_group_menu.is_comment IS '댓글 권한';
COMMENT ON COLUMN public.website_group_menu.is_download IS '파일 다운로드 권한';
COMMENT ON COLUMN public.website_group_menu.is_special IS '특수 기능 권한';
COMMENT ON COLUMN public.website_group_menu.is_use IS '행 사용 여부';
COMMENT ON COLUMN public.website_group_menu.created_id IS '등록자 FK → user.id';
COMMENT ON COLUMN public.website_group_menu.created_at IS '등록 시각';
CREATE INDEX idx_website_group_menu_group ON public.website_group_menu USING btree (group_id);
CREATE INDEX idx_website_group_menu_menu ON public.website_group_menu USING btree (menu_id);
COMMENT ON TABLE public.website_group_menu IS '그룹별 웹 메뉴 CRUD·기능 권한 (레거시 MySQL site_group_menu)';

-- public.product
CREATE TABLE public.product (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code varchar(64) NOT NULL,
	legacy_system varchar(32) NULL,
	product_legacy_code varchar(64) NULL,
	product_name varchar(255) NOT NULL,
	description text NULL,
	is_use bool DEFAULT true NOT NULL,
	remark varchar(256) NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT products_pkey PRIMARY KEY (id),
	CONSTRAINT uk_products_code UNIQUE (code),
	CONSTRAINT uk_products_legacy_mapping UNIQUE (legacy_system, product_legacy_code),
	CONSTRAINT chk_products_legacy_mapping CHECK (
		(legacy_system IS NULL AND product_legacy_code IS NULL)
		OR (legacy_system IS NOT NULL AND product_legacy_code IS NOT NULL)
	),
	CONSTRAINT fk_products_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_products_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.product.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.product.code IS '제품 업무 코드 (UK). SKU/모델 식별';
COMMENT ON COLUMN public.product.legacy_system IS '레거시 출처 시스템 식별자(예: cescoservice). product_legacy_code 와 쌍으로 사용';
COMMENT ON COLUMN public.product.product_legacy_code IS '레거시 제품/모델 코드(구 시스템 PK/업무키). 이관·양방향 조회용. 신규 연동 키는 code';
COMMENT ON COLUMN public.product.product_name IS '제품 표시명';
COMMENT ON COLUMN public.product.description IS '제품 설명 (선택, text)';
COMMENT ON COLUMN public.product.is_use IS '사용 여부. false 이면 포털·API·배치 대상에서 제외';
COMMENT ON COLUMN public.product.remark IS '내부 운영·관리 메모';
COMMENT ON COLUMN public.product.created_id IS '등록자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.product.updated_id IS '수정자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.product.created_at IS '생성 시각 (timestamp(3), 앱에서 명시 설정)';
COMMENT ON COLUMN public.product.updated_at IS '최종 수정 시각 (timestamp(3), 앱에서 명시 설정)';

CREATE INDEX idx_products_created_at ON public.product USING btree (created_at);
CREATE INDEX idx_products_is_use ON public.product USING btree (is_use);
CREATE INDEX idx_products_legacy_code ON public.product USING btree (legacy_system, product_legacy_code)
  WHERE product_legacy_code IS NOT NULL;
COMMENT ON TABLE public.product IS '제품 축. 조직 트리와 직교. device.product_id';

-- public.branch
CREATE TABLE public.branch (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code varchar(64) NOT NULL,
	legacy_system varchar(32) NULL,
	branch_legacy_code varchar(64) NULL,
	branch_type int4 DEFAULT 2 NOT NULL,
	company_id int4 NOT NULL,
	branch_name varchar(255) NOT NULL,
	description varchar(512) NULL,
	is_use bool DEFAULT true NOT NULL,
	remark varchar(256) NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT branches_pkey PRIMARY KEY (id),
	CONSTRAINT uk_branches_code UNIQUE (code),
	CONSTRAINT uk_branches_legacy_mapping UNIQUE (legacy_system, branch_legacy_code),
	CONSTRAINT chk_branches_legacy_mapping CHECK (
		(legacy_system IS NULL AND branch_legacy_code IS NULL)
		OR (legacy_system IS NOT NULL AND branch_legacy_code IS NOT NULL)
	),
	CONSTRAINT chk_branches_branch_type CHECK (branch_type IN (1, 2)),
	CONSTRAINT fk_branches_company FOREIGN KEY (company_id) REFERENCES public.company(id) ON DELETE CASCADE,
	CONSTRAINT fk_branches_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_branches_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.branch.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.branch.code IS '지점 업무 코드 (UK, 모비 SSOT)';
COMMENT ON COLUMN public.branch.legacy_system IS '레거시 출처 시스템 식별자(예: cescoservice). branch_legacy_code 와 쌍으로 사용';
COMMENT ON COLUMN public.branch.branch_legacy_code IS '레거시 지점 코드(구 시스템 PK/업무키). 이관·양방향 조회용. 신규 연동 키는 code';
COMMENT ON COLUMN public.branch.branch_type IS 'B0001 sub_code. 1=본사 지점(headquarters_branch), 2=일반 지사(regional_branch). 회사당 본사 지점 1건(부분 UK)';
COMMENT ON COLUMN public.branch.company_id IS '상위 회사 FK → company.id (CASCADE)';
COMMENT ON COLUMN public.branch.branch_name IS '지점 표시 명칭';
COMMENT ON COLUMN public.branch.description IS '지점 설명 (선택)';
COMMENT ON COLUMN public.branch.is_use IS '사용 여부. false 이면 포털·API·배치 대상에서 제외';
COMMENT ON COLUMN public.branch.remark IS '내부 운영·관리 메모';
COMMENT ON COLUMN public.branch.created_id IS '등록자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.branch.updated_id IS '수정자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.branch.created_at IS '생성 시각 (timestamp(3), 앱에서 명시 설정)';
COMMENT ON COLUMN public.branch.updated_at IS '최종 수정 시각 (timestamp(3), 앱에서 명시 설정)';

CREATE INDEX idx_branches_company_id ON public.branch USING btree (company_id);
CREATE INDEX idx_branches_branch_type ON public.branch USING btree (branch_type);
CREATE INDEX idx_branches_legacy_code ON public.branch USING btree (legacy_system, branch_legacy_code)
  WHERE branch_legacy_code IS NOT NULL;
CREATE UNIQUE INDEX uk_branches_company_headquarters ON public.branch USING btree (company_id)
  WHERE branch_type = 1;
CREATE INDEX idx_branches_is_use ON public.branch USING btree (is_use);
COMMENT ON TABLE public.branch IS '지점(본사 지점·일반 지사). B0001=branch_type. company 하위. member·notification.branch_id';

-- public.device_group
CREATE TABLE public.device_group (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	product_id int4 NOT NULL,
	code varchar(64) NOT NULL,
	device_group_name varchar(255) NOT NULL,
	description varchar(512) NULL,
	is_use bool DEFAULT true NOT NULL,
	remark varchar(256) NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT device_groups_pkey PRIMARY KEY (id),
	CONSTRAINT uk_device_groups_code UNIQUE (code),
	CONSTRAINT fk_device_groups_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_device_groups_product FOREIGN KEY (product_id) REFERENCES public.product(id) ON DELETE CASCADE,
	CONSTRAINT fk_device_groups_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.device_group.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.device_group.product_id IS '기준 제품 FK → product.id (CASCADE)';
COMMENT ON COLUMN public.device_group.code IS '디바이스 그룹 코드 (UK)';
COMMENT ON COLUMN public.device_group.device_group_name IS '그룹 표시명';
COMMENT ON COLUMN public.device_group.description IS '그룹 설명 (선택)';
COMMENT ON COLUMN public.device_group.is_use IS '사용 여부. false 이면 포털·API·배치 대상에서 제외';
COMMENT ON COLUMN public.device_group.remark IS '내부 운영·관리 메모';
COMMENT ON COLUMN public.device_group.created_id IS '등록자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.device_group.updated_id IS '수정자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.device_group.created_at IS '생성 시각 (timestamp(3), 앱에서 명시 설정)';
COMMENT ON COLUMN public.device_group.updated_at IS '최종 수정 시각 (timestamp(3), 앱에서 명시 설정)';

COMMENT ON TABLE public.device_group IS '디바이스 그룹 (제품·현장·단말 묶음)';

-- public.firmware
CREATE TABLE public.firmware (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code varchar(64) NOT NULL,
	product_id int4 NOT NULL,
	firmware_version varchar(64) NOT NULL,
	s3_key varchar(512) NULL,
	checksum varchar(128) NULL,
	size_bytes int8 NULL,
	release_notes text NULL,
	is_use bool DEFAULT true NOT NULL,
	remark varchar(256) NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT firmwares_pkey PRIMARY KEY (id),
	CONSTRAINT uk_firmwares_code UNIQUE (code),
	CONSTRAINT uk_firmwares_product_version UNIQUE (product_id, firmware_version),
	CONSTRAINT fk_firmwares_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_firmwares_product FOREIGN KEY (product_id) REFERENCES public.product(id) ON DELETE CASCADE,
	CONSTRAINT fk_firmwares_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.firmware.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.firmware.code IS '펌웨어 패키지 코드 (UK)';
COMMENT ON COLUMN public.firmware.product_id IS '대상 제품 FK → product.id (CASCADE)';
COMMENT ON COLUMN public.firmware.firmware_version IS '펌웨어 버전 문자열. UK (product_id, firmware_version)';
COMMENT ON COLUMN public.firmware.s3_key IS 'S3 객체 키 (배포 아티팩트)';
COMMENT ON COLUMN public.firmware.checksum IS '아티팩트 체크섬 (SHA256 등)';
COMMENT ON COLUMN public.firmware.size_bytes IS '파일 크기 (bytes)';
COMMENT ON COLUMN public.firmware.release_notes IS '릴리스 노트 (선택)';
COMMENT ON COLUMN public.firmware.is_use IS '사용 여부. false 이면 포털·API·배치 대상에서 제외';
COMMENT ON COLUMN public.firmware.remark IS '내부 운영·관리 메모';
COMMENT ON COLUMN public.firmware.created_id IS '등록자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.firmware.updated_id IS '수정자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.firmware.created_at IS '생성 시각 (timestamp(3), 앱에서 명시 설정)';
COMMENT ON COLUMN public.firmware.updated_at IS '최종 수정 시각 (timestamp(3), 앱에서 명시 설정)';

CREATE INDEX idx_firmwares_product_id ON public.firmware USING btree (product_id);
COMMENT ON TABLE public.firmware IS '제품별 펌웨어 버전·S3 아티팩트 메타';

-- public.site — 조직·현장 단위 SSOT (본사·지사·현장을 동일 테이블에 두되 org_level_type 으로 구분)
CREATE TABLE public.site (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code varchar(64) NOT NULL,
	legacy_system varchar(32) NULL,
	site_legacy_code varchar(64) NULL,
	org_level_type int4 DEFAULT 3 NOT NULL,
	company_id int4 NULL,
	branch_id int4 NULL,
	site_name varchar(255) NOT NULL,
	description varchar(512) NULL,
	latitude numeric(10, 7) NULL,
	longitude numeric(10, 7) NULL,
	utc_offset_hours numeric(3, 1) DEFAULT 0 NOT NULL,
	site_type int4 DEFAULT 1 NOT NULL,
	is_use bool DEFAULT true NOT NULL,
	remark varchar(256) NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT sites_pkey PRIMARY KEY (id),
	CONSTRAINT uk_sites_code UNIQUE (code),
	CONSTRAINT uk_sites_legacy_mapping UNIQUE (legacy_system, site_legacy_code),
	CONSTRAINT chk_sites_legacy_mapping CHECK (
		(legacy_system IS NULL AND site_legacy_code IS NULL)
		OR (legacy_system IS NOT NULL AND site_legacy_code IS NOT NULL)
	),
	CONSTRAINT fk_sites_company FOREIGN KEY (company_id) REFERENCES public.company(id) ON DELETE SET NULL,
	CONSTRAINT fk_sites_branch FOREIGN KEY (branch_id) REFERENCES public.branch(id) ON DELETE SET NULL,
	CONSTRAINT fk_sites_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_sites_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT chk_sites_org_level_type CHECK (org_level_type IN (1, 2, 3)),
	CONSTRAINT chk_sites_facility_type CHECK (site_type >= 1),
	CONSTRAINT chk_sites_utc_offset_hours CHECK (utc_offset_hours >= -12.0 AND utc_offset_hours <= 14.0),
	CONSTRAINT chk_sites_latitude CHECK (latitude IS NULL OR (latitude >= -90 AND latitude <= 90)),
	CONSTRAINT chk_sites_longitude CHECK (longitude IS NULL OR (longitude >= -180 AND longitude <= 180)),
	CONSTRAINT chk_sites_org_scope CHECK (
		(org_level_type = 1 AND company_id IS NOT NULL AND branch_id IS NULL)
		OR (org_level_type = 2 AND branch_id IS NOT NULL)
		OR (org_level_type = 3)
	)
);
COMMENT ON COLUMN public.site.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.site.code IS '조직·현장 업무 코드 (UK, 모비 SSOT). MQTT·ERP·시드 키 — 본사/지사/현장 공통';
COMMENT ON COLUMN public.site.legacy_system IS '레거시 출처 시스템 식별자(예: cescoservice). site_legacy_code 와 쌍으로 사용';
COMMENT ON COLUMN public.site.site_legacy_code IS '레거시 현장/조직 코드(구 site·project 키). 이관·양방향 조회용. 신규 연동 키는 code';
COMMENT ON COLUMN public.site.org_level_type IS 'S0015 sub_code. 1=본사(headquarters), 2=지사(branch_office), 3=현장(field_site). company·branch 마스터와 독립 등록 가능';
COMMENT ON COLUMN public.site.company_id IS '회사 FK(선택). 본사(org_level=1) 필수. 현장·지사는 branch 경유 또는 직접 스냅샷';
COMMENT ON COLUMN public.site.branch_id IS '지점 FK(선택). 지사(org_level=2) 필수. 현장(org_level=3)은 NULL 허용 — 지사·본사와 분리된 독립 현장';
COMMENT ON COLUMN public.site.site_name IS '표시 명칭 (알림·UI 라벨)';
COMMENT ON COLUMN public.site.description IS '부가 설명·별칭·주소 요약 등 (선택)';
COMMENT ON COLUMN public.site.latitude IS '위도 WGS84 (numeric 10,7). 7째 소수 자리 ≈ 1.1 cm — 현장·건물 단위 정밀 좌표';
COMMENT ON COLUMN public.site.longitude IS '경도 WGS84 (numeric 10,7). 위도에 따라 동서 거리 스케일은 cos(lat) 보정. 7째 소수 ≈ 1~1.4 cm(한국 위도)';
COMMENT ON COLUMN public.site.utc_offset_hours IS 'UTC 대비 시차(시간). 한국 +9.0, 인도 +5.5, 미 동부 표준 -5.0. 소수 1자리(30분 단위). DST·서머타임은 앱에서 갱신';
COMMENT ON COLUMN public.site.site_type IS 'S0001 sub_code(시설·업종 분류). 공장/물류/오피스 등 — org_level_type 과 별개';
COMMENT ON COLUMN public.site.is_use IS '사용 여부. false 이면 포털·API·배치 대상에서 제외';
COMMENT ON COLUMN public.site.remark IS '내부 운영·관리 메모';
COMMENT ON COLUMN public.site.created_id IS '등록자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.site.updated_id IS '수정자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.site.created_at IS '생성 시각 (timestamp(3), 앱에서 명시 설정)';
COMMENT ON COLUMN public.site.updated_at IS '최종 수정 시각 (timestamp(3), 앱에서 명시 설정)';

CREATE INDEX idx_sites_legacy_code ON public.site USING btree (legacy_system, site_legacy_code)
  WHERE site_legacy_code IS NOT NULL;
CREATE INDEX idx_sites_org_level_type ON public.site USING btree (org_level_type);
CREATE INDEX idx_sites_company_id ON public.site USING btree (company_id);
CREATE INDEX idx_sites_branch_id ON public.site USING btree (branch_id);
CREATE INDEX idx_sites_site_type ON public.site USING btree (site_type);
CREATE INDEX idx_sites_utc_offset_hours ON public.site USING btree (utc_offset_hours);
COMMENT ON TABLE public.site IS '조직·현장 단위 SSOT. S0015=본사/지사/현장, S0001=시설업종. branch·company FK 선택. member·device·notification.site_id';

-- public.update_job (status_type=A0009, deploy_type=A0010)
CREATE TABLE public.update_job (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code varchar(64) NOT NULL,
	product_id int4 NOT NULL,
	target_firmware_id int4 NOT NULL,
	status_type int4 DEFAULT 1 NOT NULL,
	deploy_type int4 DEFAULT 1 NOT NULL,
	group_name varchar(128) NULL,
	requested_by_id int4 NULL,
	start_at timestamp(3) NULL,
	completed_at timestamp(3) NULL,
	is_use bool DEFAULT true NOT NULL,
	remark varchar(256) NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT uk_update_jobs_code UNIQUE (code),
	CONSTRAINT update_jobs_pkey PRIMARY KEY (id),
	CONSTRAINT chk_update_job_status_type CHECK (status_type IN (1, 2, 3, 4, 5)),
	CONSTRAINT chk_update_job_deploy_type CHECK (deploy_type IN (1, 2)),
	CONSTRAINT fk_update_jobs_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_update_jobs_firmware FOREIGN KEY (target_firmware_id) REFERENCES public.firmware(id) ON DELETE RESTRICT,
	CONSTRAINT fk_update_jobs_product FOREIGN KEY (product_id) REFERENCES public.product(id) ON DELETE CASCADE,
	CONSTRAINT fk_update_jobs_requested_by FOREIGN KEY (requested_by_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_update_jobs_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.update_job.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.update_job.code IS 'OTA Job 코드 (UK)';
COMMENT ON COLUMN public.update_job.product_id IS '대상 제품 FK → product.id';
COMMENT ON COLUMN public.update_job.target_firmware_id IS '목표 펌웨어 FK → firmware.id (RESTRICT)';
COMMENT ON COLUMN public.update_job.status_type IS 'A0009 sub_code. 1=pending, 2=in_progress, 3=completed, 4=failed, 5=cancelled';
COMMENT ON COLUMN public.update_job.deploy_type IS 'A0010 sub_code. 1=direct, 2=group';
COMMENT ON COLUMN public.update_job.group_name IS '배포 대상 그룹명 (선택)';
COMMENT ON COLUMN public.update_job.requested_by_id IS '요청자 FK → user.id (SET NULL)';
COMMENT ON COLUMN public.update_job.start_at IS 'Job 시작 시각';
COMMENT ON COLUMN public.update_job.completed_at IS 'Job 완료 시각';
COMMENT ON COLUMN public.update_job.is_use IS '사용 여부. false 이면 포털·API·배치 대상에서 제외';
COMMENT ON COLUMN public.update_job.remark IS '내부 운영·관리 메모';
COMMENT ON COLUMN public.update_job.created_id IS '등록자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.update_job.updated_id IS '수정자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.update_job.created_at IS '생성 시각 (timestamp(3), 앱에서 명시 설정)';
COMMENT ON COLUMN public.update_job.updated_at IS '최종 수정 시각 (timestamp(3), 앱에서 명시 설정)';

CREATE INDEX idx_update_jobs_product_id ON public.update_job USING btree (product_id);
CREATE INDEX idx_update_jobs_status_type ON public.update_job USING btree (status_type);
COMMENT ON TABLE public.update_job IS '제품 단위 OTA/FOTA Job';

-- public.device_group_product
CREATE TABLE public.device_group_product (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	group_id int4 NOT NULL,
	product_id int4 NOT NULL,
	is_use bool DEFAULT true NOT NULL,
	remark varchar(256) NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT device_group_products_pkey PRIMARY KEY (id),
	CONSTRAINT uk_device_group_products UNIQUE (group_id, product_id),
	CONSTRAINT fk_device_group_products_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_device_group_products_group FOREIGN KEY (group_id) REFERENCES public.device_group(id) ON DELETE CASCADE,
	CONSTRAINT fk_device_group_products_product FOREIGN KEY (product_id) REFERENCES public.product(id) ON DELETE CASCADE,
	CONSTRAINT fk_device_group_products_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.device_group_product.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.device_group_product.group_id IS '디바이스 그룹 FK → device_group.id (CASCADE)';
COMMENT ON COLUMN public.device_group_product.product_id IS '제품 FK → product.id (CASCADE)';
COMMENT ON COLUMN public.device_group_product.is_use IS '사용 여부. false 이면 포털·API·배치 대상에서 제외';
COMMENT ON COLUMN public.device_group_product.remark IS '내부 운영·관리 메모';
COMMENT ON COLUMN public.device_group_product.created_id IS '등록자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.device_group_product.updated_id IS '수정자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.device_group_product.created_at IS '생성 시각 (timestamp(3), 앱에서 명시 설정)';
COMMENT ON COLUMN public.device_group_product.updated_at IS '최종 수정 시각 (timestamp(3), 앱에서 명시 설정)';

COMMENT ON TABLE public.device_group_product IS '디바이스 그룹 ↔ 제품 N:M';

-- public.device_group_site
CREATE TABLE public.device_group_site (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	group_id int4 NOT NULL,
	site_id int4 NOT NULL,
	is_use bool DEFAULT true NOT NULL,
	remark varchar(256) NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT device_group_sites_pkey PRIMARY KEY (id),
	CONSTRAINT uk_device_group_sites UNIQUE (group_id, site_id),
	CONSTRAINT fk_device_group_sites_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_device_group_sites_group FOREIGN KEY (group_id) REFERENCES public.device_group(id) ON DELETE CASCADE,
	CONSTRAINT fk_device_group_sites_site FOREIGN KEY (site_id) REFERENCES public.site(id) ON DELETE CASCADE,
	CONSTRAINT fk_device_group_sites_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.device_group_site.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.device_group_site.group_id IS '디바이스 그룹 FK → device_group.id (CASCADE)';
COMMENT ON COLUMN public.device_group_site.site_id IS '현장 FK → site.id (CASCADE)';
COMMENT ON COLUMN public.device_group_site.is_use IS '사용 여부. false 이면 포털·API·배치 대상에서 제외';
COMMENT ON COLUMN public.device_group_site.remark IS '내부 운영·관리 메모';
COMMENT ON COLUMN public.device_group_site.created_id IS '등록자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.device_group_site.updated_id IS '수정자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.device_group_site.created_at IS '생성 시각 (timestamp(3), 앱에서 명시 설정)';
COMMENT ON COLUMN public.device_group_site.updated_at IS '최종 수정 시각 (timestamp(3), 앱에서 명시 설정)';

COMMENT ON TABLE public.device_group_site IS '디바이스 그룹 ↔ 현장 N:M';

-- public.device
CREATE TABLE public.device (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	device_code varchar(64) NOT NULL,
	hub_code varchar(64) NULL,
	site_id int4 NULL,
	product_id int4 NOT NULL,
	serial varchar(128) NOT NULL,
	device_phase_main_code varchar(5) DEFAULT 'D0001'::character varying NOT NULL,
	device_phase_sub_code int4 DEFAULT 1 NOT NULL,
	operational_status_type int4 DEFAULT 1 NOT NULL,
	firmware_version varchar(64) NULL,
	firmware_id int4 NULL,
	last_seen_at timestamp(3) NULL,
	is_use bool DEFAULT true NOT NULL,
	remark varchar(256) NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT devices_pkey PRIMARY KEY (id),
	CONSTRAINT uk_device_device_code UNIQUE (device_code),
	CONSTRAINT uk_devices_site_product_serial UNIQUE (site_id, product_id, serial),
	CONSTRAINT chk_device_operational_status_type CHECK (operational_status_type IN (1, 2)),
	CONSTRAINT fk_devices_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_devices_firmware FOREIGN KEY (firmware_id) REFERENCES public.firmware(id) ON DELETE SET NULL,
	CONSTRAINT fk_devices_product FOREIGN KEY (product_id) REFERENCES public.product(id) ON DELETE CASCADE,
	CONSTRAINT fk_devices_site FOREIGN KEY (site_id) REFERENCES public.site(id) ON DELETE SET NULL,
	CONSTRAINT fk_devices_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.device.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.device.device_code IS '단말 문자열 고유값 (UK). DocumentDB·MQTT 토픽 SSOT';
COMMENT ON COLUMN public.device.hub_code IS '허브 경유 시 허브 식별자 (선택)';
COMMENT ON COLUMN public.device.site_id IS '배치 현장 FK → site.id (SET NULL). 출고 전 NULL 가능';
COMMENT ON COLUMN public.device.product_id IS '제품 FK → product.id (CASCADE)';
COMMENT ON COLUMN public.device.serial IS '단말 시리얼. UK (site_id, product_id, serial)';
COMMENT ON COLUMN public.device.device_phase_main_code IS '단말 단계 그룹 common_code (DEF D0001)';
COMMENT ON COLUMN public.device.device_phase_sub_code IS 'D0001 sub_code (운영/시험 등)';
COMMENT ON COLUMN public.device.operational_status_type IS 'A0011 sub_code. 1=operational, 2=non_operational';
COMMENT ON COLUMN public.device.firmware_version IS '단말 보고 펌웨어 버전 문자열 (표시용)';
COMMENT ON COLUMN public.device.firmware_id IS '정본 펌웨어 FK → firmware.id (SET NULL)';
COMMENT ON COLUMN public.device.last_seen_at IS '최근 통신 시각. 통신 품질·온라인 판단';
COMMENT ON COLUMN public.device.is_use IS '사용 여부. false 이면 포털·API·배치 대상에서 제외';
COMMENT ON COLUMN public.device.remark IS '내부 운영·관리 메모';
COMMENT ON COLUMN public.device.created_id IS '등록자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.device.updated_id IS '수정자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.device.created_at IS '생성 시각 (timestamp(3), 앱에서 명시 설정)';
COMMENT ON COLUMN public.device.updated_at IS '최종 수정 시각 (timestamp(3), 앱에서 명시 설정)';

CREATE INDEX idx_devices_hub_code ON public.device USING btree (hub_code);
CREATE INDEX idx_devices_product_id ON public.device USING btree (product_id);
CREATE INDEX idx_devices_site_id ON public.device USING btree (site_id);
COMMENT ON TABLE public.device IS '단말. device_code=MQTT·DocDB SSOT. 출고 전 site_id NULL 가능. D0001 단계 common_code';

-- public.firmware_update_history
CREATE TABLE public.firmware_update_history (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code varchar(64) NOT NULL,
	device_id int4 NOT NULL,
	job_id int4 NULL,
	from_firmware_id int4 NULL,
	to_firmware_id int4 NOT NULL,
	status_type int4 NOT NULL,
	error_message text NULL,
	completed_at timestamp(3) NULL,
	is_use bool DEFAULT true NOT NULL,
	remark varchar(256) NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT firmware_update_history_pkey PRIMARY KEY (id),
	CONSTRAINT uk_firmware_update_history_code UNIQUE (code),
	CONSTRAINT chk_firmware_update_history_status_type CHECK (status_type IN (1, 2, 3, 4)),
	CONSTRAINT fk_fuh_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_fuh_device FOREIGN KEY (device_id) REFERENCES public.device(id) ON DELETE CASCADE,
	CONSTRAINT fk_fuh_from_firmware FOREIGN KEY (from_firmware_id) REFERENCES public.firmware(id) ON DELETE SET NULL,
	CONSTRAINT fk_fuh_job FOREIGN KEY (job_id) REFERENCES public.update_job(id) ON DELETE SET NULL,
	CONSTRAINT fk_fuh_to_firmware FOREIGN KEY (to_firmware_id) REFERENCES public.firmware(id) ON DELETE RESTRICT,
	CONSTRAINT fk_fuh_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.firmware_update_history.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.firmware_update_history.code IS '이력 업무 코드 (UK)';
COMMENT ON COLUMN public.firmware_update_history.device_id IS '단말 FK → device.id (CASCADE)';
COMMENT ON COLUMN public.firmware_update_history.job_id IS '연관 OTA Job FK → update_job.id (SET NULL)';
COMMENT ON COLUMN public.firmware_update_history.from_firmware_id IS '이전 펌웨어 FK (SET NULL)';
COMMENT ON COLUMN public.firmware_update_history.to_firmware_id IS '목표 펌웨어 FK (RESTRICT)';
COMMENT ON COLUMN public.firmware_update_history.status_type IS 'A0012 sub_code. 1=pending, 2=success, 3=failed, 4=skipped';
COMMENT ON COLUMN public.firmware_update_history.error_message IS '실패 시 오류 메시지';
COMMENT ON COLUMN public.firmware_update_history.completed_at IS '단말별 완료 시각';
COMMENT ON COLUMN public.firmware_update_history.is_use IS '사용 여부. false 이면 포털·API·배치 대상에서 제외';
COMMENT ON COLUMN public.firmware_update_history.remark IS '내부 운영·관리 메모';
COMMENT ON COLUMN public.firmware_update_history.created_id IS '등록자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.firmware_update_history.updated_id IS '수정자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.firmware_update_history.created_at IS '생성 시각 (timestamp(3), 앱에서 명시 설정)';
COMMENT ON COLUMN public.firmware_update_history.updated_at IS '최종 수정 시각 (timestamp(3), 앱에서 명시 설정)';

COMMENT ON TABLE public.firmware_update_history IS '단말별 펌웨어 업데이트 이력';

-- public.update_job_device_status_event
CREATE TABLE public.update_job_device_status_event (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	job_id int4 NOT NULL,
	device_id int4 NOT NULL,
	event_kind_type int4 DEFAULT 2 NOT NULL,
	device_status varchar(32) NULL,
	firmware_version varchar(64) NULL,
	error_message text NULL,
	request_timestamp varchar(24) NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT update_job_device_status_events_pkey PRIMARY KEY (id),
	CONSTRAINT chk_ujdse_event_kind_type CHECK (event_kind_type IN (1, 2)),
	CONSTRAINT fk_ujdse_device FOREIGN KEY (device_id) REFERENCES public.device(id) ON DELETE CASCADE,
	CONSTRAINT fk_ujdse_job FOREIGN KEY (job_id) REFERENCES public.update_job(id) ON DELETE CASCADE
);
COMMENT ON COLUMN public.update_job_device_status_event.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.update_job_device_status_event.job_id IS 'OTA Job FK → update_job.id (CASCADE)';
COMMENT ON COLUMN public.update_job_device_status_event.device_id IS '단말 FK → device.id (CASCADE)';
COMMENT ON COLUMN public.update_job_device_status_event.event_kind_type IS 'A0013 sub_code. 1=requested, 2=status';
COMMENT ON COLUMN public.update_job_device_status_event.device_status IS '단말 보고 상태 문자열';
COMMENT ON COLUMN public.update_job_device_status_event.firmware_version IS '보고 펌웨어 버전';
COMMENT ON COLUMN public.update_job_device_status_event.error_message IS '오류 메시지 (선택)';
COMMENT ON COLUMN public.update_job_device_status_event.request_timestamp IS '단말 요청 시각 문자열 (원문 보존)';
COMMENT ON COLUMN public.update_job_device_status_event.created_at IS '이벤트 수신·적재 시각';

CREATE INDEX idx_ujdse_job_device_created ON public.update_job_device_status_event USING btree (job_id, device_id, created_at);
COMMENT ON TABLE public.update_job_device_status_event IS 'OTA Job·단말 상태/버전 이벤트 스트림';

-- public.update_job_device
CREATE TABLE public.update_job_device (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	job_id int4 NOT NULL,
	device_id int4 NOT NULL,
	status_type int4 DEFAULT 1 NOT NULL,
	error_message text NULL,
	reported_version varchar(64) NULL,
	completed_at timestamp(3) NULL,
	is_use bool DEFAULT true NOT NULL,
	remark varchar(256) NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT uk_update_job_devices UNIQUE (job_id, device_id),
	CONSTRAINT update_job_devices_pkey PRIMARY KEY (id),
	CONSTRAINT chk_update_job_device_status_type CHECK (status_type IN (1, 2, 3, 4)),
	CONSTRAINT fk_update_job_devices_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_update_job_devices_device FOREIGN KEY (device_id) REFERENCES public.device(id) ON DELETE CASCADE,
	CONSTRAINT fk_update_job_devices_job FOREIGN KEY (job_id) REFERENCES public.update_job(id) ON DELETE CASCADE,
	CONSTRAINT fk_update_job_devices_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.update_job_device.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.update_job_device.job_id IS 'OTA Job FK → update_job.id (CASCADE)';
COMMENT ON COLUMN public.update_job_device.device_id IS '단말 FK → device.id (CASCADE)';
COMMENT ON COLUMN public.update_job_device.status_type IS 'A0014 sub_code. 1=pending, 2=in_progress, 3=success, 4=failed';
COMMENT ON COLUMN public.update_job_device.error_message IS '실패 메시지';
COMMENT ON COLUMN public.update_job_device.reported_version IS '단말 보고 버전';
COMMENT ON COLUMN public.update_job_device.completed_at IS '단말별 완료 시각';
COMMENT ON COLUMN public.update_job_device.is_use IS '사용 여부. false 이면 포털·API·배치 대상에서 제외';
COMMENT ON COLUMN public.update_job_device.remark IS '내부 운영·관리 메모';
COMMENT ON COLUMN public.update_job_device.created_id IS '등록자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.update_job_device.updated_id IS '수정자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.update_job_device.created_at IS '생성 시각 (timestamp(3), 앱에서 명시 설정)';
COMMENT ON COLUMN public.update_job_device.updated_at IS '최종 수정 시각 (timestamp(3), 앱에서 명시 설정)';

COMMENT ON TABLE public.update_job_device IS 'OTA Job 대상 단말별 진행 행';

-- public.device_group_device
CREATE TABLE public.device_group_device (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	group_id int4 NOT NULL,
	device_id int4 NOT NULL,
	is_use bool DEFAULT true NOT NULL,
	remark varchar(256) NULL,
	created_id int4 NULL,
	updated_id int4 NULL,
	created_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	updated_at timestamp(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
	CONSTRAINT device_group_devices_pkey PRIMARY KEY (id),
	CONSTRAINT uk_device_group_devices UNIQUE (group_id, device_id),
	CONSTRAINT fk_device_group_devices_created FOREIGN KEY (created_id) REFERENCES public."user"(id) ON DELETE SET NULL,
	CONSTRAINT fk_device_group_devices_device FOREIGN KEY (device_id) REFERENCES public.device(id) ON DELETE CASCADE,
	CONSTRAINT fk_device_group_devices_group FOREIGN KEY (group_id) REFERENCES public.device_group(id) ON DELETE CASCADE,
	CONSTRAINT fk_device_group_devices_updated FOREIGN KEY (updated_id) REFERENCES public."user"(id) ON DELETE SET NULL
);
COMMENT ON COLUMN public.device_group_device.id IS 'Surrogate PK (GENERATED BY DEFAULT AS IDENTITY)';
COMMENT ON COLUMN public.device_group_device.group_id IS '디바이스 그룹 FK → device_group.id (CASCADE)';
COMMENT ON COLUMN public.device_group_device.device_id IS '단말 FK → device.id (CASCADE)';
COMMENT ON COLUMN public.device_group_device.is_use IS '사용 여부. false 이면 포털·API·배치 대상에서 제외';
COMMENT ON COLUMN public.device_group_device.remark IS '내부 운영·관리 메모';
COMMENT ON COLUMN public.device_group_device.created_id IS '등록자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.device_group_device.updated_id IS '수정자 FK → public."user".id (ON DELETE SET NULL)';
COMMENT ON COLUMN public.device_group_device.created_at IS '생성 시각 (timestamp(3), 앱에서 명시 설정)';
COMMENT ON COLUMN public.device_group_device.updated_at IS '최종 수정 시각 (timestamp(3), 앱에서 명시 설정)';

COMMENT ON TABLE public.device_group_device IS '디바이스 그룹 ↔ 단말 N:M';

-- -----------------------------------------------------------------------------
-- "user" 레거시 현장 스코프 → site FK (신규 RBAC 는 member.site_id)
-- -----------------------------------------------------------------------------
ALTER TABLE public."user"
  ADD CONSTRAINT fk_users_scope_site FOREIGN KEY (scope_site_id) REFERENCES public.site(id) ON DELETE SET NULL;


